### ISSUE TITLE
Community Blogs feedback & suggestions

### ISSUE THREAD

**Issue by tomaarsen** [huggingface/hub-docs#1007]
Hello!

Yesterday I had the pleasure to release a community blogpost, and I have a few comments on the topic:
1. Only the last three community blogposts are reasonably accessible by any user, the others can only be seen by endlessly clicking on the ">" arrow until you happen to find the blogpost that you're interested in. I would have expected a separate page or tab for these blogs, e.g. just like how NLP has a [separate tab](https://huggingface.co/blog?tag=nlp).
2. I'd love to be able to optionally select an image as the preview, specifically for rich embeds when linking to the blogpost. Right now the embed is:
![image](https://github.com/huggingface/hub-docs/assets/37621491/f96ba41c-3b64-414e-a695-23c5c12f662f)

3. I'd love to be able to see some analytics of the blogpost as the author.
4. The "Community" tab in the blog page is now somewhat confusing, as it doesn't actually have "Community blogposts".
5. Collaboration is not possible - I understand that this is a lot of work for little reward, but the option to add other authors via metadata would already be very valuable.
6. The maximum title length is quite low, I had to rephrase a few tiles to try and get it to fit. It didn't use `...` when it was the first blogpost, but now it does:
![image](https://github.com/huggingface/hub-docs/assets/37621491/985c6e38-3282-4b27-9b8a-d08bcac15581)

Points 2 and 5 should be possible if the format from https://github.com/huggingface/blog is adopted, e.g. 
```
---
title: "Non-engineers guide: Train a LLaMA 2 chatbot"
thumbnail: /blog/assets/78_ml_director_insights/tuto.png
authors:
- user: 2legit2overfit
- user: abhishek
---
```
from [here](https://raw.githubusercontent.com/huggingface/blog/f6f151a7f7ce1efd581e2dc95928852c5234b75f/Llama2-for-non-engineers.md).

- Tom Aarsen

**Comment by julien-c** [comment]
useful feedback, thanks!

**Comment by lunarflu** [comment]
Thanks for the feedback Tom! Some thoughts for everyone:

#1 Is it possible to add mouse scrolling horizontally, without changing the rest of the visuals? Might be a more atomic / simpler way to improve (also consistent with how users navigate many other pages we have). 

#3 Could be nice to motivate bloggers, also to track impact over time (do we already have something like this internally?)

**Comment by julien-c** [comment]
i think for point 1 it's better to design a separate, "view all", page

**Comment by tomaarsen** [comment]
Point 2 has been improved - the rich embed now included the title like so:
![image](https://github.com/huggingface/hub-docs/assets/37621491/4214ec0b-3858-4b18-b230-b653c317d6cc)

Great job with this!

**Comment by osanseviero** [comment]
With https://huggingface.co/blog/community , this issue is now done :fire:
