### ISSUE TITLE
GitHub: Add link to documentation

### ISSUE THREAD

**Issue by stefan-it** [huggingface/hub-docs#1026]
Hi,

it would be great if a link to the model hub documentation could be added to the "About" info of this repository.

For example, the peft repository has the following information:

![image](https://github.com/huggingface/hub-docs/assets/20651387/a0a8ea43-7d36-459c-841c-c7b49d49aab7)

For this repository a link to "https://huggingface.co/docs/hub"  could be added resulting in this:

![image](https://github.com/huggingface/hub-docs/assets/20651387/dfce707f-3d78-4f1b-89a8-3fd371dd21f2)

**Comment by osanseviero** [comment]
Great idea! Done! :fire: :rocket:
