### ISSUE TITLE
Inference API snippets are cut-off on smaller screens.

### ISSUE THREAD

**Issue by Vaibhavs10** [huggingface/hub-docs#1038]
Coming over from the discussion in #1030 

The snippet displayed for models with extra pre-processing required on top of the just receiving the output from the API is hidden on smaller screens.

Snippet from [SDXL-base](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0?inference_api=true)
<img width="1023" alt="image" src="https://github.com/huggingface/hub-docs/assets/18682411/63bc3222-2661-4e32-bf1a-d007436a6f67">

I'm on a 13 inch MBP, testing on the primary screen.

This currently effects all `Text-to-Image`, `Text-to-Audio`, & `Text-to-Speech` models on the hub that are compatible with `inference-api` or `inference-api-community`

cc: @osanseviero @mishig25 🤗

**Comment by osanseviero** [comment]
Friendly ping to @mishig25 and @gary149

**Comment by mishig25** [comment]
do you have screenshot on the smaller screen and what's being hidden?

**Comment by Vaibhavs10** [comment]
If you click on the SDXL-base URL mentioned on the original post (and open on a bigger screen) you'll see the rest of the code snippet.

The screenshot in the message above was taken on a smaller screen and has incomplete code.

**Comment by mishig25** [comment]
on smal screen, you can still scroll the element to the right. no?

![image](https://github.com/huggingface/hub-docs/assets/11827707/65b22989-6c86-48ca-8ad9-a1900698db72)

**Comment by gary149** [comment]
> on smal screen, you can still scroll the element to the right. no?

I think the problem is it doesnt vertical scroll ?

**Comment by osanseviero** [comment]
You cannot vertically scroll from within the code snippet. So for example, in my screen the code snippet might look like this. As you can see, part of it is cut/not displayed

<img width="812" alt="Screenshot 2023-11-08 at 14 23 42" src="https://github.com/huggingface/hub-docs/assets/7246357/ca63d8fd-732e-4d68-af7b-5d2525d6ea90">

**Comment by osanseviero** [comment]
Thanks!
