### ISSUE TITLE
Reset password link not working

### ISSUE THREAD

**Issue by 5hayanB** [huggingface/hub-docs#1072]
I have lost my password for my account. After receiving the password reset link on my email, clicking the reset link redirects me to the "Send password reset email" page.

![image](https://github.com/huggingface/hub-docs/assets/91522269/4841ca88-f394-4d4f-ac9d-d88f26eee7ca)

Are the reset links broken?

**Comment by julien-c** [comment]
they seem to work, can you send an email to website@ instead? cc @meganriley for viz
