### ISSUE TITLE
Missing `Text2Text generation` task

### ISSUE THREAD

**Issue by mishig25** [huggingface/hub-docs#108]
Is one of them supposed to be `Text2text generation` task? 

<img width="800" alt="Screenshot 2022-04-19 at 15 03 10" src="https://user-images.githubusercontent.com/11827707/164010380-23824705-2a60-4e32-b029-d6a01ca57b44.png">

**Comment by osanseviero** [comment]
They are actually considered the same task for the purpose of the content, it was actually an accident of  a recent PR that made it show duplicated.
