### ISSUE TITLE
 Text-Classification Pipeline does not show the text in the widget

### ISSUE THREAD

**Issue by canberk17** [huggingface/hub-docs#1083]
Hey guys, I've encountered an issue  when I tried  to use the widget in model cards  for text classification.  Here are the details:

 I'm experiencing an issue with the **Text-Classification**  pipeline in my model card, particularly with my project [ckandemir/bitcoin_tweet_sentiment_classification](https://huggingface.co/ckandemir/bitcoin_tweet_sentiment_classification?text=Sold+all+btc%2C+tethered+up+before+the+correction.). 

When  I provide the text I want to show on the widget  to my README.md  and select  text-classification as pipeline( or AutoDetect), the widget does not show the text. However, when I change the pipeline to  **Token-Classification**  it does show the text as default.

Here are the examples:

This is when the pipeline is set to: text-classification 
![Screenshot 2023-11-05 at 11 11 22 PM](https://github.com/huggingface/hub-docs/assets/33362633/241431ee-e717-4e51-b144-0a15d035f373)

This is when the pipeline is set to: token-classification 

![Screenshot 2023-11-05 at 11 11 52 PM](https://github.com/huggingface/hub-docs/assets/33362633/1588d70e-f604-4130-85ab-a324ac51ae4e)

**Describe the solution you'd like**
The ideal solution would be for the widget to display the provided text in the `README.md` file  by default when the pipeline is set to **Text-Classification**

@mishig25

**Comment by julien-c** [comment]
maybe ping @mishig25

**Comment by julien-c** [comment]
Thanks for reporting this, @canberk17!

**Comment by canberk17** [comment]
Of course! Thank you for the quick fix, and this amazing community! @julien-c @mishig25
