### ISSUE TITLE
[content] copy part of the audio and images datasets doc

### ISSUE THREAD

**Issue by severo** [huggingface/hub-docs#1106]
In the "Datasets" section of the Hub docs, we explain how to create different types of datasets. But for the audio and image datasets (https://huggingface.co/docs/hub/datasets-data-files-configuration#image-and-audio-datasets) we just send to the `datasets` library docs.

The issue is that the https://huggingface.co/docs/datasets/audio_dataset and https://huggingface.co/docs/datasets/image_dataset pages are very long and very specific to the datasets library.

I think that we should extract the relevant "no-code" part to paste into the Hub docs, and refer to the datasets pages only for "advanced setup".

**Comment by lhoestq** [comment]
makes sense !

**Comment by severo** [comment]
I'll work on it

**Comment by severo** [comment]
Also:
- create a example datasets collection, as https://huggingface.co/collections/datasets-examples/image-dataset-6568e7cf28639db76eb92d65
- mention the example datasets collections in the docs
