### ISSUE TITLE
Clarify if hardware type is equal to hardware requirements in the specification

### ISSUE THREAD

**Issue by dgarijo** [huggingface/hub-docs#1121]
**Is your feature request related to a problem? Please describe.**
We are reviewing the [model card specification](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md) in order to adopt it. However, `Hardware Type` and `hardware requirements` have the same key `hardware`. We believe these entries are not the same, as I can require 2 GB of RAM and 2 H100 GPUs for running a model, but the the hardware_type is just `GPU H100`. Can you please clarify the intended use in the current documentation? (for hardware requirements there is no definition)

**Describe the solution you'd like**
Clarify if `hardware_type` and `hardware requirements` are mapped to the same key `hardware`

Thanks!

**Comment by pcuenca** [comment]
Interesting! My understanding is that "hardware type" times the "hours" gives an approximation for the total amount of compute, which is a very interesting figure to report. What do you think is important to cover in the "hardware requirements" field? cc @davanstrien for insight.

**Comment by davanstrien** [comment]
I think @EziOzoani and @meg-huggingface are probably the best people to answer this.

**Comment by meg-huggingface** [comment]
Thank you so much for noticing this issue, @dgarijo !
Following your thoughts, we have now broken `hardware` into:
```
hardware_type
hardware_requirements
```
The updated template is here:
https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md

**Comment by dgarijo** [comment]
Thanks! Closing the issue then
