### ISSUE TITLE
Update doc with `funded_by`

### ISSUE THREAD

**Issue by dgarijo** [huggingface/hub-docs#1122]
**Is your feature request related to a problem? Please describe.**
We have identified an inconsistency in the documentation: 
- https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/modelcard_template.md contains `funded_by`
- https://huggingface.co/docs/hub/model-card-annotated does not have `funded_by`

**Describe the solution you'd like**
Update https://huggingface.co/docs/hub/model-card-annotated with `funded_by`

**Comment by osanseviero** [comment]
cc @EziOzoani @meg-huggingface
