### ISSUE TITLE
Outdated Repository About information

### ISSUE THREAD

**Issue by bhavberi** [huggingface/hub-docs#1142]
The About section of the repository is outdated and needs to be updated as per the new repository and codebase restructuring to huggingface.js

Current:
![image](https://github.com/huggingface/hub-docs/assets/43399374/95e916ec-3379-408a-93ed-c74587bed1c1)

Suggested:
Documentation and information hosted on the Hugging Face website.

Related to #1140

**Comment by julien-c** [comment]
good catch! what do you suggest?

**Comment by julien-c** [comment]
i've kept things simple for now:

<img width="1230" alt="image" src="https://github.com/huggingface/hub-docs/assets/326577/be8b8652-cd38-4c51-91a5-3e330979d880">
