### ISSUE TITLE
`adapter-transformers`  deprecated and replaced by `adapters`

### ISSUE THREAD

**Issue by Hamza-nabil** [huggingface/hub-docs#1171]
**Doc request**
Update the documentation for [Using Adapter Transformers at Hugging Face](https://huggingface.co/docs/hub/adapter-transformers) .

**Additional context**
The  `adapter-transformers`  is deprecated and replaced by new package `adapters` . See [Introducing Adapters](https://adapterhub.ml/blog/2023/11/introducing-adapters/)  for more information.

**Comment by julien-c** [comment]
ah i had not seen this announcement. Thanks for sharing! An exciting development.

@arueckle @JoPfeiff @hSterz @calpt do you want to work together to revamp/update this documentation? (cc @osanseviero too)

**Comment by calpt** [comment]
hey, thanks for bringing this up and pinging, happy to work together on updating this. We'll look into it in the next couple of days.

**Comment by calpt** [comment]
I've drafted an updated docs page in #1184.

**Comment by bmuskalla** [comment]
@calpt Seems like this issue can be closed or is there anything left to do?

**Comment by Hamza-nabil** [comment]
@bmuskalla  looks good to close!
 
 Thank you everyone
