### ISSUE TITLE
Improve search on papers page

### ISSUE THREAD

**Issue by Vipitis** [huggingface/hub-docs#1176]
was directed to open the issue here.

The [papers page](https://huggingface.co/papers) has this search for "arxiv id or title". What really bothers me, is that pasting the full arxiv link (or even pdf link) does not find the paper.

**Current workaround**:
manually delete all characters before and after the arxiv id.

Should be a small change

**Example:**
![not working](https://github.com/huggingface/hub-docs/assets/23384483/a86a1a0e-0e09-4acc-b568-e82442f2ae51)
![working](https://github.com/huggingface/hub-docs/assets/23384483/91e9a4b6-c71d-43ec-a324-ac9c3a86d981)

**Comment by julien-c** [comment]
maybe cc @mishig25!

**Comment by julien-c** [comment]
thanks for reporting @Vipitis can you confirm it works fine now?

**Comment by Vipitis** [comment]
I tested this earlier today. It works with arxiv links, arxiv pdf links and even hf papers links.  Thanks for getting this added this quickly 🤗
