### ISSUE TITLE
Document HuggingFace's SSH fingerprints

### ISSUE THREAD

**Issue by ikmckenz** [huggingface/hub-docs#1198]
**Doc request**
When first connecting to HuggingFace over SSH to do a git clone of a model, I get the classic message:
```
The authenticity of host 'hf.co (34.198.14.237)' can't be established.
ED25519 key fingerprint is SHA256:dVjzGIdV7d6cwKIeZiCoRMa2gMvSKfGZAvHf4gMiMao.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```
And after connecting, the key entry in my `known_hosts` file looks like: 
```
hf.co ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJjhgtT9FOQrsVSarIoPVI1jFMh3VSHdKfdqp/O776s
```
Searching around, I can't easily find HF's SSH fingerprints publicly documented to verify them. It would be nice to be able to verify them. 

**Additional context**
GitHub's SSH key fingerprints are publicly documented here, for a comparison: https://docs.github.com/en/enterprise-cloud@latest/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints

**Comment by julien-c** [comment]
maybe cc @XciD @rtrompier

**Comment by XciD** [comment]
https://github.com/huggingface/hub-docs/pull/1203

**Comment by ikmckenz** [comment]
Looks like the above PR is merged, and I now see the keys publicly. Thank you! Closing now.
