### ISSUE TITLE
When we are viewing the docs, we want to edit(fix) the page.

### ISSUE THREAD

**Issue by zzz6519003** [huggingface/hub-docs#1273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by julien-c** [comment]
yes actually, i think we've wanted to link from each doc page to its source on GitHub for a long time, no @mishig25 @gary149?

**Comment by mishig25** [comment]
yes, should I do this ?

![Screenshot 2024-04-22 at 11 39 11](https://github.com/huggingface/hub-docs/assets/11827707/68253291-cde8-4310-9cf2-5044cafca68c)

**Comment by mishig25** [comment]
fixed by https://github.com/huggingface/doc-builder/pull/498

https://github.com/huggingface/hub-docs/assets/11827707/3f414334-3a73-4122-92a2-59bcc882f677
