### ISSUE TITLE
Change to HuggingFace API for Repo Access Management?

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/hub-docs#1276]
**Bug description.**
A few days ago, my scripts for querying a list of access requests for repos stopped working. The repos can no longer be found.

**Describe the expected behaviour**
Previously I could make curl requests and get a list of access requests and then control access.

Has something changed?

**Comment by julien-c** [comment]
Hi Rowan, do you know which specific endpoint/call?

**Comment by RonanKMcGovern** [comment]
Ah very sorry @julien-c  , I just realised I rolled my HF token after a live stream last week without realising it was being used in some automations. Thanks for the quick reply.
