### ISSUE TITLE
Update the `GGUF usage with llama.cpp` doc page

### ISSUE THREAD

**Issue by julien-c** [huggingface/hub-docs#1277]
there's now way cleaner syntax than https://huggingface.co/docs/hub/en/gguf-llamacpp to load a model from HF in llama.cpp

**Comment by cakiki** [comment]
This is resolved by https://github.com/huggingface/hub-docs/pull/1280 right?

**Comment by julien-c** [comment]
hmm no only partly i think

https://huggingface.co/docs/hub/en/gguf-llamacpp is still sub-optimal imo.

cc @Vaibhavs10, and also cc @ngxson who opened https://github.com/huggingface/huggingface.js/pull/778 which is the same command(s) but "in-product" (on the Hub) vs. in a doc

**Comment by Vaibhavs10** [comment]
Good catch, will open a PR today to update and ask for everyone's reviews! 👍

**Comment by Vaibhavs10** [comment]
Opened a PR to discuss: https://github.com/huggingface/hub-docs/pull/1326

cc: @ngxson - I wasn't able to add you as a reviewer, but please feel free to review

**Comment by cakiki** [comment]
@julien-c now it can be closed I guess :smiley_cat:

**Comment by julien-c** [comment]
yes we can close but @Vaibhavs10 @ngxson i would still add how to install (recommend brew etc) to [that doc page](https://huggingface.co/docs/hub/en/gguf-llamacpp) WDYT?

Closing in the meantime
