### ISSUE TITLE
Inference widget consumes wrong mask token

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#131]
Hello 👋 

I hope this is the right repository to open issue to. 🤞 

[This model](https://huggingface.co/uw-madison/nystromformer-4096) takes [MASK] token (as seen in special_token_names.json) but mask token is taken as < mask > which makes widget fail.

**Comment by osanseviero** [comment]
Hi there :wave: The mask token does not come from `special_token_names.json` afaik. 

They can be:
* Specified in the metadata of the repo
* Automatically retrieved as seen in

```
export const MAPPING_MASK_TOKENS = new Map([
	["[MASK]", ["distilbert", "albert", "bert", "electra"]],
	["<mask>", ["camembert", "xlm-roberta", "bart", "longformer", "roberta", "xlnet", "amazon/bort"]],
	["<special1>", ["xlm", "flaubert"]],
]);
```
Internal code https://github.com/huggingface/moon-landing/blob/93d758a5d5a23f97c7f0029520db347dd3ce0641/server/repo_types/ModelInfo.ts

cc @mishig25

**Comment by julien-c** [comment]
very true sir!

**Comment by osanseviero** [comment]
Closing as no follow-up is needed here
