### ISSUE TITLE
[Feature request] filter datasets by num_rows

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#1315]
Now that the number of rows is part of the metadata available to parquet datasets, it would be nice if the sorting menu for datasets could use that information and allow users to sort datasets in a profile by number of rows.

![image](https://github.com/huggingface/hub-docs/assets/3664563/8dc37fa1-98d6-4021-bb82-5c94307c9196)

**Comment by julien-c** [comment]
wdyt @cakiki? =)

**Comment by cakiki** [comment]
Love the search feature @julien-c ! 

I don't think it's possible to sort by num_rows though, is it?

**Comment by krampstudio** [comment]
> I don't think it's possible to sort by num_rows though, is it?

It's not yet deployed, it will be available today

**Comment by cakiki** [comment]
Love it!

![image](https://github.com/huggingface/hub-docs/assets/3664563/d16ddf84-5a77-48af-b9e0-fbd2b90039d3)

**Comment by julien-c** [comment]
lol yeah i posted a bit too early, or more precisely on my machine i live in the future =)
