### ISSUE TITLE
Issue in inferencing Custom Spacy ner model from HuggingFace

### ISSUE THREAD

**Issue by JeswinMS4** [huggingface/hub-docs#1372]
I had uploaded my NER model trained through Spacy on huggingface. While trying to inference, I am facing this issue:

    pip install https://huggingface.co/JeswinMS4/en_resume_pipeline/resolve/main/en_resume_pipeline-any-py3-none-any.whl

> ERROR: Invalid requirement: 'en-resume-pipeline==any': Expected end or
> semicolon (after name and no valid version specifier)
>     en-resume-pipeline==any
>                       ^

The documentation also states this way to load. Is there anything I am missing out?

**Comment by Wauplin** [comment]
Replied in https://github.com/explosion/spacy-huggingface-hub/issues/22#issuecomment-2286025815 (dupliated issue). Unfortunately, I can't tell what's the issue you are facing but I don't think it has to do with the Hugging Face Hub or the Spacy integration.

**Comment by Wauplin** [comment]
Closing this issue as per https://github.com/explosion/spacy-huggingface-hub/issues/22#issuecomment-2286127600
