### ISSUE TITLE
Can't link to huggingface.co from Spaces

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#140]
### Describe the bug

Linking to any page (without a _blank target) on the huggingface.co domain leads to a "huggingface.co refused to connect." message.

### Reproduction

To reproduce: create a new static page and remove the target="_blank" from the already pre-populated anchor tag. (It's what I did here: https://huggingface.co/spaces/cakiki/test Try clicking on "Spaces documentation")

### System Info

```shell
Google Chrome: Version 101.0.4951.54 (Official Build) (64-bit)
```

**Comment by osanseviero** [comment]
Seems same as https://github.com/huggingface/moon-landing/issues/2693

**Comment by Nana12345678910** [comment]
Cards says code error

**Comment by cakiki** [comment]
@Nana12345678910 If you're referring to the link Omar shared, it's a private repository.
