### ISSUE TITLE
We need more information about Model tree

### ISSUE THREAD

**Issue by Light1Smile** [huggingface/hub-docs#1410]
**Doc request**
  I am very pleased that Hugging Face recently added the Model Tree, a really cool feature, and I believe it's a great tool for studying Model Reuse. However, I haven’t found much information in Hugging Face's documentation to better understand and use it. For example, information on all types of finetuning and the criteria for distinguishing them; how to retrieve all relevant finetuned models based on the model name via the API. I want to iterate on this to build a complete reuse network. As far as I know, adding a basemodel to the metadata will generate a Model Tree, and models with GGUF files are considered Quantizations, etc.

  I hope there is relevant documentation available. If so, please provide the corresponding documentation links. If there is an API to call the Model Tree, please provide the related documentation. If not, I hope it can be developed and made available soon. Thank you very much.

**Additional context**
![image](https://github.com/user-attachments/assets/4881c44f-4d9b-4589-944f-983e914f0b06)

**Comment by osanseviero** [comment]
cc @Wauplin @SBrandeis @Vaibhavs10

**Comment by NielsRogge** [comment]
+1, in favor of having a tiny "learn more" button at each model tree which links to the docs.

**Comment by julien-c** [comment]
> ```
> model = model_info(model_id)
> model.card_data.get("base_model")
> ```

not the best way because you don't get support for redirects of rename, etc

Better to get the `baseModel` in the model API directly
