### ISSUE TITLE
Permalinks to transformers.PreTrainedModel.from_pretrained attributes are broken in releases starting from 4.41.0/v4.41.1/v4.41.2/v4.41.3 EN

### ISSUE THREAD

**Issue by alcompa** [huggingface/hub-docs#1420]
## Bug description.
Permalinks to transformers.PreTrainedModel.from_pretrained attributes are broken in releases starting from `v4.41.0/v4.41.1/v4.41.2/v4.41.3 EN`.

### Example: `.config` attribute
![image](https://github.com/user-attachments/assets/762ea52c-0dc5-40d0-af60-6f1bb62d8282)

Clicking the permalink icon redirects to `https://huggingface.co/docs/transformers/v4.41.3/en/main_classes/&amp;num;transformers.PreTrainedModel.from_pretrained.config`

which says: 
> "The documentation page MAIN_CLASSES/&NUM;TRANSFORMERS.PRETRAINEDMODEL.FROM_PRETRAINED.CONFIG doesn’t exist in v4.41.3, but exists on the main version. Click [here](https://huggingface.co/docs/transformers/main/en/main_classes/&num;transformers.PreTrainedModel.from_pretrained.config) to redirect to the main version of the documentation."

Clicking on "here" redirects to a 404.

## Expected behaviour
In previous versions, e.g. `v4.40.0/v4.40.1/v4.40.2 EN` this feature works properly. 
Creating a permalink for `transformers.PreTrainedModel.from_pretrained.config` results in the following URL `https://huggingface.co/docs/transformers/v4.40.2/en/main_classes/model#transformers.PreTrainedModel.from_pretrained.config`

**Comment by julien-c** [comment]
@mishig25 maybe (idk)

**Comment by mishig25** [comment]
It was fixed by @gante https://github.com/huggingface/doc-builder/pull/516. This problem no longer exists on newer versions of the docs.

@gante you can re-trigger doc-build jobs for versions 4.41.0/v4.41.1/v4.41.2/v4.41.3 to fix them
