### ISSUE TITLE
Wrong Task Mentioned in Text

### ISSUE THREAD

**Issue by ecyht2** [huggingface/hub-docs#1423]
**This repository is focused on the Hub experience and documentation. If you're facing an issue with a specific library, please open an issue in the corresponding GitHub repo. If you're facing an issue with a specific model or dataset, please open an issue in the corresponding HF repo.**

**Bug description.**
I notice the task mentioned is wrong in the line `185` of `docs/source/en/tasks_explained.md`

**Describe the expected behaviour**
The task should be `image segmentation` instead of `object detection`

**Additional context**

```
Ready to try your hand at object detection? Check out our complete [image segmentation guide](tasks/semantic_segmentation) to learn how to finetune SegFormer and use it for inference!
```

should be

```
Ready to try your hand at image segmentation? Check out our complete [image segmentation guide](tasks/semantic_segmentation) to learn how to finetune SegFormer and use it for inference!
```

**Comment by pcuenca** [comment]
cc @merveenoyan

**Comment by merveenoyan** [comment]
@ecyht2 would you like to open a PR?
