### ISSUE TITLE
Incompatibility with SuperNova-Medius-GGUF model in Ollama integration docs

### ISSUE THREAD

**Issue by lucianoayres** [huggingface/hub-docs#1451]
The recently updated documentation on Ollama integration lists the hf.co/arcee-ai/SuperNova-Medius-GGUF model as an example:

`ollama run hf.co/arcee-ai/SuperNova-Medius-GGUF`

However, attempting to run this command results in the following error:

`Error: pull model manifest: 400: Repository is not GGUF or is not compatible with llama.cpp`

This issue only occurs with the SuperNova-Medius-GGUF model. Other models mentioned in the documentation function as expected (see attached screenshot).

![Screenshot from 2024-10-16 16-17-20](https://github.com/user-attachments/assets/25743cbd-e2e4-4319-9cf4-99dac94a2019)

**Comment by Vaibhavs10** [comment]
Thanks for the report @lucianoayres - we're looking into it. I can reproduce the error on my end as well.
cc: @ngxson

**Comment by Vaibhavs10** [comment]
This should work now @lucianoayres - please feel free to close the issue if it works for you as well.
![image](https://github.com/user-attachments/assets/ec841ede-74bc-4aa7-8179-7b2cf401857f)

**Comment by lucianoayres** [comment]
Worked like a charm, @Vaibhavs10 Thank you 🤗
