### ISSUE TITLE
Bookmarklet available 

### ISSUE THREAD

**Issue by hololeo** [huggingface/hub-docs#1456]
created a bookmarklet for this great resource. just click 'n' ollamarun

https://github.com/hololeo/click-n-ollamarun

**Comment by julien-c** [comment]
cool project! 

did you see we added a snippet to copy/paste to the "Use this model" dropdown on model pages for ollama?

<img width="1239" alt="image" @mishig25 "https://github.com/user-attachments/assets/9b699707-fcce-45ab-bd71-2f6868b76e53">

cc @mishig25 @ngxson

**Comment by mishig25** [comment]
hello @hololeo,

awesome project! You can get ollama snippets from the model page as well

![ollama-modelpage-dark](https://github.com/user-attachments/assets/b836b5dc-6e5c-4904-9c00-5811a2b30120)

I've just updated the docs too: https://huggingface.co/docs/hub/ollama

**Comment by hololeo** [comment]
those are nice additions and animations are lovely!

**Comment by julien-c** [comment]
thanks for the kind words @hololeo
