### ISSUE TITLE
GenerationConfig parameters are deleted from the website on 4.52.2 and main

### ISSUE THREAD

**Issue by eyalmazuz** [huggingface/hub-docs#1460]
**This repository is focused on the Hub experience and documentation. If you're facing an issue with a specific library, please open an issue in the corresponding GitHub repo. If you're facing an issue with a specific model or dataset, please open an issue in the corresponding HF repo.**

**Bug description.**
When opening the documentation for [v4.52.2](https://huggingface.co/docs/transformers/v4.45.2/en/main_classes/text_generation) or [main](https://huggingface.co/docs/transformers/main/en/main_classes/text_generation) about GenerationConfig, the first thing it shows it the ``from_pretrained`` method and not the various kwargs you can set for generation.

Image for example:
![image](https://github.com/user-attachments/assets/af542f9e-d56b-4312-94fb-ecac57be8d1e)

**Describe the expected behaviour**
When checking [v4.42.2](https://huggingface.co/docs/transformers/v4.44.2/en/main_classes/text_generation)
The first thing it shows is the "Parameters that control the length of the output"

Image for example:

![image](https://github.com/user-attachments/assets/f9eb5060-5f7b-4ce2-a344-18bc9e1f9391)

**Comment by julien-c** [comment]
Hi! this should be reported on the `transformers` repo

**Comment by eyalmazuz** [comment]
> Hi! this should be reported on the `transformers` repo

I first wanted to open there but the option "Webiste-related" redirects to this repo

![image](https://github.com/user-attachments/assets/1c7a9e09-5f25-4c90-b0fe-ded8925829a7)

but I'll open the issue there

thank you
