### ISSUE TITLE
Download statistics only show last two weeks of downloads (periodically appearing bug)

### ISSUE THREAD

**Issue by Lauler** [huggingface/hub-docs#154]
Hi!

The "Downloads last month" statistics for models on huggingface.co are occasionally affected by a bug where the download numbers for the first two weeks of the month are zeroed out for all models on the entire website. In other words: the "downloads last month" number only takes in to account the latter half of the month. 

This seems to happen periodically (at least once a month). The faulty statistics last for 1-3 days and then the problem will typically resolve itself, with the stats and downloads from the first half of the month reappearing again. 

Here are some screenshots on the plot and download numbers for the current top 3 models, for the purposes of documenting how they look like before the download statistics and plots go back to normal again:

## https://huggingface.co/gpt2
![image](https://user-images.githubusercontent.com/7157234/169412082-5fb52368-9f1e-41c3-8f7a-9348334e55a0.png)

## https://huggingface.co/distilgpt2
![image](https://user-images.githubusercontent.com/7157234/169412221-a993e9c2-2f93-4ded-a4f6-85065c26a115.png)

## https://huggingface.co/bert-base-uncased
![image](https://user-images.githubusercontent.com/7157234/169410665-b4a6bd1c-0701-49c8-bd2e-1f095e8b7d81.png)

For reference, here are the listed download numbers for the top 10 most downloaded models on huggingface the last **two weeks**: 

![image](https://user-images.githubusercontent.com/7157234/169411297-275a29ab-2972-40c9-be56-1b0abdb12e6a.png)

These numbers will all jump up higher when this issue resolves itself, since huggingface.co then once again will start counting the first half of the month.

Every month I run a script to log the download numbers of my organization's models. This is the reason I noticed that this was a periodically appearing bug in the first place. Whenever this bug is in effect, I need to wait a day or two before it resolves itself before I can run my script to scrape the download numbers.

**Comment by osanseviero** [comment]
cc @julien-c @Pierrci

**Comment by julien-c** [comment]
pinging @co42 on this! Do you have an idea Corentin?

**Comment by co42** [comment]
@julien-c My bad, fixing

**Comment by co42** [comment]
Fixed in prod.
PR : https://github.com/huggingface/moon-landing/pull/2988

**Comment by Lauler** [comment]
The graphs look like normal again (how I remember them from before the bug). 

However, all the "downloads last month" numbers were higher by a factor of 2 to 3 for our models a couple of days ago. Was there a change in how the numbers are tabulated @co42 ?

![image](https://user-images.githubusercontent.com/7157234/169516261-d52a6b7a-a710-46de-abfc-9764d6d60460.png)

Download numbers for all top 10 models dropped by a lot after fix. Maybe counting all usages from a single user as only 1 use  now or something?

**Comment by Lauler** [comment]
See archive.org Wayback machine from May 12th as reference: 

https://web.archive.org/web/20220512124207/https://huggingface.co/models

![image](https://user-images.githubusercontent.com/7157234/169517411-9e19fb3e-95ed-4544-84f8-0a99b40e893a.png)

**Comment by co42** [comment]
@Lauler, the graph was fixed but not the total. It is now :)

**Comment by Lauler** [comment]
Thank you! Much appreciated that you took the time to fix this issue.

It would be really nice if Huggingface could prioritize adding a feature to show historical download statistics for models further back than 1 month. Download numbers are very useful statistic to be able to show for many organizations when for example applying for grants, or for access to HPC resources.

**Comment by osanseviero** [comment]
For internal reference, we have an internal issue for this https://github.com/huggingface/moon-landing/issues/1340

**Comment by julien-c** [comment]
The fix was actually not deployed in prod, but it should be from today on. (cc @Pierrci )

Tentatively closing this again, reopen if still happens in the coming days =) =)
