### ISSUE TITLE
Easy to fix bug due to wrong redirection link.

### ISSUE THREAD

**Issue by bhanu-pm** [huggingface/hub-docs#1542]
**Bug description.**
In the [getting started](https://huggingface.co/docs/api-inference/getting-started) page of api-inference docs. Users get redirected to [this](https://huggingface.co/docs/api-inference/parameters.md) non-existing page instead of [this](https://huggingface.co/docs/api-inference/parameters) parameters url.

**Easy fix**
Just replacing the link with the correct link should fix the issue.

**Comment by pcuenca** [comment]
Thanks a lot @bhanu-pm! Would you like to submit a PR to fix it, so you are credited with the resolution? You'd need to change [this line](https://github.com/huggingface/hub-docs/blob/aeb7f4be8822dedd58c1ad8e273bf7bf56a22c05/docs/api-inference/getting-started.md?plain=1#L95C79-L95C82). No worries if you don't have time; we'll do it next week instead.

**Comment by bhanu-pm** [comment]
Wow @pcuenca that is such a kind gesture. I would love to do that!
