### ISSUE TITLE
Highlight "Add User" button

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#158]
**Is your feature request related to a problem? Please describe.**
The `Add User` button blends in and is difficult to spot for people who don't know it exists.

**Describe the solution you'd like**
Moving the button next to the `Email link` button or perhaps a different color to highlight it?

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/3664563/170666134-c93da111-814a-4ea4-9b45-84246bef0584.png)

**Comment by gary149** [comment]
Do users report it? it feels a bit weird to have that button in the join settings IMO.

**Comment by osanseviero** [comment]
I agree it's a bit weird in join settings. WDYT next to Organization members?

![Screenshot from 2022-06-02 11-39-39](https://user-images.githubusercontent.com/7246357/171602292-47a3a9cb-3416-49c0-8178-fcbae13e4439.png)

**Comment by osanseviero** [comment]
I think it is better now that "Add user" is immediately next to "Organization Members". WDYT.
