### ISSUE TITLE
Research the need for a recommended YAML formatting convention for repo card metadata

### ISSUE THREAD

**Issue by julien-c** [huggingface/hub-docs#164]
Just used this PR to create a automatic PR creation (70 PRs), see: https://huggingface.co/Helsinki-NLP/opus-mt-tc-big-zls-en/discussions/1 

The code I used was pretty simple:

```py
#!/usr/bin/env python3
from huggingface_hub import hf_api
from huggingface_hub.repocard import metadata_update

hf_api = hf_api.HfApi()

all_marian_models = hf_api.list_models(filter="marian")
all_new_marian_models = [x.modelId for x in all_marian_models if x.modelId.startswith("Helsinki-NLP/opus-mt-tc")]

for repo_id in all_new_marian_models:
    print(f"Opening PR for {repo_id}")
    metadata_update(repo_id, {"tags": ["translation", "opus-mt-tc"]}, create_pr=True, pr_commit_summary="Add `opus-mt-tc` tag", pr_commit_description="Add `opus-mt-tc` tag so that this new marian models can be found more easily")
```

One small problem though is that the YAML layout was changed a bit unnecessarily (as you can see here: https://huggingface.co/Helsinki-NLP/opus-mt-tc-big-zls-en/discussions/1/files). Can we maybe make sure that we enforce the same YAML format everywhere across our codebases to not format from one type to another?

cc @julien-c @LysandreJik @osanseviero

_Originally posted by @patrickvonplaten in https://github.com/huggingface/huggingface_hub/issues/884#issuecomment-1143344415_

**Comment by julien-c** [comment]
- on Python side we use latest release of `pyyaml` and `yaml.dump(data, sort_keys=False, line_break=line_break)` where `line_break` is the line break detected from the file (when it exists before) defaulting to `\n`

**Comment by osanseviero** [comment]
Closing this for now

**Comment by julien-c** [comment]
thanks, i think it's not needed anymore but cc'ing @Wauplin for visibility as this was before his time IIRC

**Comment by Wauplin** [comment]
> on Python side we use latest release of pyyaml and yaml.dump(data, sort_keys=False, line_break=line_break) where line_break is the line break detected from the file (when it exists before) defaulting to \n

To be complete, now we use `yaml.dump(data, sort_keys=False, line_break=line_break, stream=None, allow_unicode=True)`. Haven't seen much issues around yaml dumps so I guess we can close yes
