### ISSUE TITLE
A HF Courses Portal

### ISSUE THREAD

**Issue by lbourdois** [huggingface/hub-docs#179]
Hi :)

As the name of the issue suggests, I think it would be interesting to have an educational/courses portal on the website.
What I mean by this is that when you click on the button circled in red in the image below, instead of referring you to the course, it would send you to a page (which I call "portal" here) that would summarise the various educational resources offered by Hugging Face.

![image](https://user-images.githubusercontent.com/58078086/171922356-4cca704a-646c-4595-9004-f009155e21fb.png)

The Hugging Face team will redesign this as they see fit from a UX/technical point of view, but here is an image of what it might look like to illustrate the idea:

![image](https://user-images.githubusercontent.com/58078086/171922831-30df0930-499a-4c56-bc7c-c2b5fc3d65bd.png)

The first line represents resources already available but not necessarily well referenced:
- The "**Natural Language Processing (NLP)**" part would refer to the actual course:
https://huggingface.co/course/chapter1/1 (GitHub repo: https://github.com/huggingface/course). 

- The "**Reinforcement Learning (RL)**" part would link to the GitHub repo: https://github.com/huggingface/deep-rl-class.
A web page will probably have to be created at some point. According to what @simoninithomas was able to tell me, the course is still in the process of being run and built with the community, so this would only be considered later as part of a V2 of the course.

- The "**Toolkit Research**" part would refer to the GitHub repo: https://github.com/huggingface/education-toolkit.
Here again, it might be necessary at some point to create a page on the site rather than simply linking to a GitHub repository.

- The "**Research**" part would link to the "Research" type articles of the blog: https://huggingface.co/blog?tag=research
For those who are interested in exploring things even deeper than the various courses (e.g. https://huggingface.co/blog/how_many_data_points/ or https://huggingface.co/blog/reformer or https://huggingface.co/blog/wav2vec2-with-ngram, etc.).

The second line represents resources that do not currently exist and are only proposals, you may have other ideas internally (I saw this on Twitter for example: https://twitter.com/mervenoyann/status/1531661622758068224?cxt=HHwWgMC-ya-Ix8EqAAAA):

- The "**Computer Vision (CV)**"
A dedicated CV course can be envisaged (ConvNet approach + Transformer approach + combination of the two ?). A dedicated GitHub repo should be created.

- The "**Audio**"
A dedicated audio course can be envisaged (ConvNet approach + Transformer approach + combination of the two ?). A dedicated GitHub repo should be created.

- The "**News about Education**"
Perhaps an "Education" filter should be created on the blog that would summarise the various education-related announcements (programmes, upcoming events, democratization tours, etc.).

- The "**Various**"
The section where things that could not be put elsewhere would be grouped (e.g. recordings of videos of Study Group Session events from the Discord like https://www.youtube.com/watch?v=cAviRhkqdnc&list=PLo2EIpI_JMQtOQK_B4G97yn1QWZ4Xi4Tu or https://www.youtube.com/watch?v=B057nftt6OU&list=PLo2EIpI_JMQtzihdW5N41acQDuUlbCi1D / https://johko.notion.site/johko/Hugging-Face-Computer-Vision-Study-Group-f0a8b75abf9f46f494131f4b223ca7a7)

I don't know what you think of this suggestion.

Have a nice day,

**Comment by julien-c** [comment]
Thanks for sharing, and wow, there's even a mockup!  Yes, this is something that we'll want to do at some point i think 👍

**Comment by lbourdois** [comment]
I close this issue now that hf.co/learn is available ✨

**Comment by osanseviero** [comment]
Yeees! :fire:

**Comment by julien-c** [comment]
thanks for the feature request!
