### ISSUE TITLE
Add docs on Hub organisations

### ISSUE THREAD

**Issue by lewtun** [huggingface/hub-docs#22]
As described in [this](https://discuss.huggingface.co/t/how-do-organizations-work/8918?u=lewtun) forum comment, the Hub [docs](https://huggingface.co/docs/hub/main) are currently a bit sparse on:

* Searching for existing orgs
* How to join an org
* What features are available between free vs premium subscriptions

It would be nice to integrate this feedback into the docs.

**Comment by osanseviero** [comment]
This is now done with new docs
