### ISSUE TITLE
CSS bug: tasks section gets cut in home page on smaller screens

### ISSUE THREAD

**Issue by hichemfantar** [huggingface/hub-docs#245]
Tasks section clearly get cut on smaller screens with no way to scroll through it horizontally.
![image](https://user-images.githubusercontent.com/34947993/178851376-37df93e9-797b-4371-9b9e-62fbdbf3a3f5.png)

**Comment by osanseviero** [comment]
cc @gary149 @beurkinger

**Comment by hichemfantar** [comment]
@gary149 tested on windows and android, chrome v103
![Screenshot_20220718-134705.jpg](https://user-images.githubusercontent.com/34947993/179514594-73a10de3-cd33-46bc-8579-b647e0cfa3a7.jpg)

**Comment by gary149** [comment]
Oh yes sorry I missed the screenshot, it's not supposed to be scrollable here :)

**Comment by hichemfantar** [comment]
Fixed by making the list vertical.
Changed this `class="flex space-x-2 -ml-16 md:-ml-0"`
to this `class="flex flex-wrap justify-center space-x-2 -ml-0 md:-ml-0"`
![image](https://user-images.githubusercontent.com/34947993/179518832-9ddf6dc6-04b2-4958-ab64-158754112006.png)
![image](https://user-images.githubusercontent.com/34947993/179520008-814f19ee-001e-480e-8730-97f65f31596a.png)

**Comment by hichemfantar** [comment]
Any movement on this? The solution I provided works on all screen sizes and It's one simple line.

**Comment by gary149** [comment]
The idea of this homepage section is to tell users about the [tasks page](https://huggingface.co/tasks). It's not meant to be an exhaustive list of available tasks. It should not take more vertical space than it does today, maybe we could add a horizontal scroll to it but I'm not even sure it's necessary.

**Comment by hichemfantar** [comment]
The vertical list doesn't take up much space.
As you can see below, it all fits inside the viewport.
![image](https://user-images.githubusercontent.com/34947993/181767850-fab5567b-5848-444e-9bc4-162dfdd2fa97.png)

**Comment by gary149** [comment]
Might add all the available tasks + horizontal scroll in a future update. Thanks for your feedback 👍
