### ISSUE TITLE
DOI Generation for Artifacts

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#25]
It would be useful to be able to generate a [Digital Object Identifier](https://en.wikipedia.org/wiki/Digital_object_identifier) to artifacts living on the Hub.

It would **let people cite a specific dataset or a specific model, and make their own datasets and models citable**. Some venues require DOIs for digital resources and it would be nice to not have to use 3rd parties for that.

Kaggle, for instance, currently has that feature for public datasets: https://www.kaggle.com/product-feedback/108594

**Drawback:** It costs money, because one has to go through approved agencies (e.g.: https://datacite.org/feemodel.html)

Automation would probably be straightforward: [Creating DOIs with the Datacite REST API](https://support.datacite.org/docs/api-create-dois)

**Comment by julien-c** [comment]
BTW (because this subject came up again recently), i remember trying to ping some DOI registrants last year and it looked very bureaucratically complex, TBH

Maybe at some point someone wants to give this another shot, but be aware this will probably be a long endeavour :)

**Comment by davanstrien** [comment]
> BTW (because this subject came up again recently), i remember trying to ping some DOI registrants last year and it looked very bureaucratically complex, TBH
> 
> Maybe at some point someone wants to give this another shot, but be aware this will probably be a long endeavour :)

One possible stop-gap solution (mainly applicable to models) could be to create a GitHub Action that in response to a webhook (or on a schedule), downloads a snapshot of a repository and pushes it to a [Zenodo](https://zenodo.org/) repository via their API.  

This would require manual setup for those wanting to use it but would be a route to getting a citable and versioned DOI for their model and has the added benefit of creating a 'preservation' copy of the model. This extra copy is also quite desirable for some communities. 

This would be a little bit hands-on for people to set up but could give a sense of how many people want this kind of feature. Full integration between Zenodo like the one with GitHub would be great, but I think this would be much more involved to establish. 

I have it on my todo list to set up something similar to push models from https://huggingface.co/BritishLibraryLabs to https://bl.iro.bl.uk/. I will ping this thread when I get around to that in case it is helpful for other people.

**Comment by cakiki** [comment]
Fantastic idea @davanstrien ! It would still require some organization and negotiation (zenodo limits uploads to 50GB I believe), but substantially less bureaucratic hassle I'm sure than dealing with registrars.

**Comment by julien-c** [comment]
maybe we could try again to see how to provide DOIs directly now. (I feel like syncing to Zenodo is a bit less elegant and depending on dataset size not sure how well it will work)

Will try to sync up with the https://datacite.org/ team in the coming weeks

**Comment by julien-c** [comment]
@cakiki would you want to participate to a call with them?

**Comment by cakiki** [comment]
@julien-c I would love to; thank you for including me!

Another thing to try would be to reach out to Kaggle and ask about their experience. They also had it [requested by users](https://www.kaggle.com/general/49445) before they added the [DOI feature](https://www.kaggle.com/product-feedback/108594) to datasets.

**Comment by yoshitomo-matsubara** [comment]
@julien-c @cakiki 
I'm here just to say thank you (including those involving [this thread)](https://twitter.com/yoshitomo_cs/status/1556989422079336449) for revisiting this issue
Providing DOIs directly (upon request? like Kaggle does) sounds like a great idea!

**Comment by julien-c** [comment]
Ok we're now officially working on this 🔥 

No ETA yet but it seems to be not-super-hard to do =)

On a related subject we can embed a "How to cite" button to those model or dataset repos where the authors will have generated a DOI. Supporting the full https://citation-file-format.github.io/about/ citation file format is maybe a bit overkill for now, so I was thinking to maybe just generate BibTeX snippet for the repos that have a DOI. Any other citation format we should support? WDYT?

**Comment by BramVanroy** [comment]
This is awesome! Very glad to hear it. Will it take commit/tag into consideration, or just one DOI per repo for now? (Which is also already awesome!)

Bibtex should be a good start (there are plenty of online bibtext-to-X converters). However, I do notice that Github seems to provide both the Bibtex and APA. E.g., on [transformers](https://github.com/huggingface/transformers) on the sidebar, when you click on "Cite this repository":

![cite this repo](https://user-images.githubusercontent.com/2779410/186413452-ba8b7746-1d3d-44ff-83ad-65e92434c236.png)

This is also described in the [Github docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).

**Comment by yoshitomo-matsubara** [comment]
I'm so glad to hear the update! 🙏
+1 for bibtex and +1 for citation UX like those @cakiki mentioned :)

**Comment by Ahleroy** [comment]
+1 for Bibtex. 
Zbib.org is a great example of easy-to-use ref export. They offer  Copy / Download buttons and RIS / Bibtex exports.
https://zbib.org/

@julien-c I would be happy to have a chat to discuss how I can contribute to this feature.

Alix

**Comment by julien-c** [comment]
Hi everyone!! We just launched DOI generation on the HuggingFace Hub, thanks to DataCite, @Kakulukian @sashavor @cakiki and @Ahleroy 🔥 

### Here's a blogpost about the feature: https://huggingface.co/blog/introducing-doi

Please try assigning DOIs to some of your repo(s) on the Hub and post any feedback here! Thank you 🤗

**Comment by yoshitomo-matsubara** [comment]
It's great news!
Many thanks to the team for making this happen!

**Comment by cakiki** [comment]
Thank you everyone; really happy this is now a feature! :hugs:

**Comment by michaelfeil** [comment]
@cakiki The DOI currently attributes the Huggingface Org name as `author`. 

Can you make them editable?

```
@misc {gradient_ai_2024, # this name is not unique
	author       = { {Gradient AI} }, # no edits possible
	title        = { Llama-3-8B-Instruct-Gradient-1048k (Revision 84c083a) }, 
	year         = 2024,
	url          = { https://huggingface.co/gradientai/Llama-3-8B-Instruct-Gradient-1048k },
	doi          = { 10.57967/hf/3372 },
	publisher    = { Hugging Face }
}
```

**Comment by cakiki** [comment]
@michaelfeil See: https://github.com/huggingface/hub-docs/issues/453
