### ISSUE TITLE
BLOOM model mentioned in hub-docs

### ISSUE THREAD

**Issue by Muhammad-Ahmad-Ghani** [huggingface/hub-docs#252]
<h3>The model mentioned in Hugging-face hub is actually 176B parameters model by BLOOM. But written as 175B</h3>

![image](https://user-images.githubusercontent.com/63394104/179976308-46ecf0d0-41b8-44e8-bc19-c6c1d60d2969.png)

**Comment by osanseviero** [comment]
Hey there! From which place is this screenshot?

**Comment by julien-c** [comment]
do you want to open a PR to fix that, @Muhammad-Ahmad-Ghani? it's in the /docs folder in https://github.com/huggingface/transformers
