### ISSUE TITLE
Highlight more 3rd party integrations, including datasets

### ISSUE THREAD

**Issue by NimaBoscarino** [huggingface/hub-docs#253]
As per these [Slack messages](https://huggingface.slack.com/archives/C03969VA7NK/p1657833574593559)

> "we should absolutely have an equivalent page to https://huggingface.co/docs/hub/models-libraries with library integrations.
i.e. we shouldn't promote "just" model library integrations but all kind of integrations"

Starting with a page for datasets integrations would be good, and then we can expand to other things as well.

**Comment by osanseviero** [comment]
This is now done in https://huggingface.co/docs/hub/datasets-libraries
