### ISSUE TITLE
Make the filter *less* fuzzy or rank exact matches higher

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/hub-docs#258]
On the model hub page, we can easily search for specific models. It seems that this filter has been created for maximal usability - trying to protect users from accidental typos. In other words, some fuzzy matching seems to be going on behind the scenes. However, this can have adverse side effects.

A prominent example is that there is a "[robbert](https://huggingface.co/pdelobelle/robBERT-base)" model (Dutch RoBERTa). So I would expect to be able to easily find this with the query "robbert". However, instead I get [results](https://huggingface.co/models?sort=downloads&search=robbert) of more widely used models - all with "roberta" in their name (so clearly not an exact match).

One approach to improve this would be to rank exact (lower-case) matches higher than fuzzy matches.

**Comment by julien-c** [comment]
Could potentially be solved by (⚠️  internal tracker) https://github.com/huggingface/moon-landing/pull/2964

**Comment by osanseviero** [comment]
This has been long updated. The `robbert` example should work now, but if you face any issues let us know! :rocket:
