### ISSUE TITLE
Add docs about library name

### ISSUE THREAD

**Issue by coyotte508** [huggingface/hub-docs#264]
cc @osanseviero @philschmid @julien-c 

There is no `library_name` mentioned in https://huggingface.co/docs/hub/models-cards

The library name is added to the tags of the model on the hub. It's determined as such:

1. The user can force `library_name` in the model card
2. If one of the tags in the model card already is a library name, then do nothing
3. We try to autodetect based on the presence of files for diffusers, keras, sklearn and nemo
4. Lastly, if nothing was detected and there is a valid `config.json` file, the library name is set to `"transformers"`

**Comment by osanseviero** [comment]
Totally! I can take this one :)
