### ISSUE TITLE
Transferring models/stuff Organization to Organization does not work

### ISSUE THREAD

**Issue by asier-gutierrez** [huggingface/hub-docs#28]
As you can see on the following image, the dropdown is disabled. I tried to remove de "disabled" attribute using Chrome Development Console but the dropdown does not contain the organization I want to make the transfer to. I am member of both organizations.

![image](https://user-images.githubusercontent.com/14359241/137745833-a704ca2d-c086-4bfb-9622-b068b798066b.png)

**Comment by osanseviero** [comment]
This is now possible, so closing this issue
