### ISSUE TITLE
Code strings in dark theme gradio not readable

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/hub-docs#280]
This is a small styling issue. When using a dark theme, inline `code` is not readable in the gradio Spaces. As an example, you can look at [SacreBLEU](https://huggingface.co/spaces/evaluate-metric/sacrebleu) where there's a readability issue in the metric description.

![code string with dark theme](https://user-images.githubusercontent.com/2779410/184106220-dbb39dbd-828a-4aae-8add-f3365fc78b35.png)

Or [here](https://huggingface.co/spaces/evaluate-metric/exact_match).

**Comment by osanseviero** [comment]
cc @abidlabs as it's more of a Gradio issue afaik

**Comment by BramVanroy** [comment]
Related issue, for prosperity: https://github.com/gradio-app/gradio/issues/1746

**Comment by BramVanroy** [comment]
@osanseviero I think this was fixed on gradio's side although I am not sure if it is 100% fixed; the issue is closed but @aliabid94 mentions that he'll polish dark mode this week. So maybe it is best to wait a little longer.

I any case, if this is fixed, it would seem that all gradio apps (at least the official ones) will need a gradio version bump in their config file.

**Comment by osanseviero** [comment]
I don't think doing a Gradio upgrade to all Spaces is straightforward, as there are some backwards compatibility issues. 

I agree we should likely do it for the official ones (cc @abidlabs @AK391 @aliabd @julien-c)
