### ISSUE TITLE
[License request] CC-BY-NC-SA 2.0

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#281]
I wasn't sure where to open this issue, so I opened here since that's where license information is listed.

A particular dataset I was adding is licensed `cc-by-nc-sa-2.0` but using this in the README returns a `YAML Metadata error`.

**Comment by osanseviero** [comment]
Feel free to open a PR to add it to https://github.com/huggingface/hub-docs/blob/main/docs/hub/repositories-licenses.md. I will do the corresponding PR internally.
