### ISSUE TITLE
🚀Display (and enable filtering by) size / number of parameters 

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#29]
**Is your feature request related to a problem? Please describe.**
It is hard to tell how big a model is without going to the repo and seeing the size of the weights file. 

**Describe the solution you'd like**
It might prove useful to be able to sort models by size or number of parameters, especially for people with more modest compute budgets. Perhaps even display that information alongside a model's popularity.

**Describe alternatives you've considered**
Alternatives would be prior knowledge of the distilled / small model landscape. This feature might also help people discover new models they hadn't heard of by enabling filtering queries like "most popular and smallest model trained using MLM on wikitext"

**Additional context**
The datasets tab has a similar feature with the `Size` category filter.

**Comment by osanseviero** [comment]
This is now done for all repos with safetensors files

**Comment by julien-c** [comment]
(filtering is API-only for now)
