### ISSUE TITLE
Allow uploading large files via the web UI

### ISSUE THREAD

**Issue by josephrocca** [huggingface/hub-docs#3]
**Is your feature request related to a problem? Please describe.**
I tried to upload a 13GB dataset file (for [this repo](https://huggingface.co/datasets/rocca/sims4-faces)), and after waiting a couple of hours for it to upload, it gave a "Payload too large" error.

**Describe the solution you'd like**
I'd like to be able to upload large dataset files using the web UI.

**Describe alternatives you've considered**
I'm guessing there's some sort of command line tool for cases like this, but I'd prefer to not have to install something just to upload a file - it's bad UX. There's no fundamental technical reason why the web UI can't handle large files, so it doesn't seem like a good idea to put limits like this in place.

**Additional info**
If the team is for some reason adamant about not allowing upload of large files via the web UI, then at the very least it would be good to stop the user with an error when they pick the file, rather than after the upload is complete. I.e. check the size of the blob with JS before uploading rather than uploading and checking size on the server.

If it's actually already possible to upload large files via the web UI (and I've just misunderstood the process), then please consider this issue a request for better UX in guiding the user toward doing that. After creating the dataset repo I just clicked across to the "files and versions" tab, and then clicked "Add file > Upload file".

Thanks!

**Comment by julien-c** [comment]
yay!!

**Comment by josephrocca** [comment]
Awesome!! :rocket: :pray:
