### ISSUE TITLE
Getting Error while Starting Sparksession

### ISSUE THREAD

**Issue by Ahmetemintek** [huggingface/hub-docs#30]
Hello, I am trying to create new streamlit app on HuggingFace by using pyspark in it. <br/>
I've created app.py file, requirement.txt file and I run a basic streamlit app without pyspark and it worked seamlessly. <br/>
However, problem starts when I add the following line `spark = SparkSession.builder.appName("appName").getOrCreate()` to start sparksession, I got an error like following: <br/>
` Exception: Java gateway process exited before sending its port number`

The content of requirements.txt file: <br/>
```
streamlit
pyspark==3.1.2
spark-nlp==3.3.2
```
If Anyone worked with pyspark on hf can help me I would be appreciate!

**Comment by osanseviero** [comment]
Closing this as it seems stale
