### ISSUE TITLE
Dark theme color issue

### ISSUE THREAD

**Issue by osbm** [huggingface/hub-docs#304]
Hello, amazing :hugs: people. [This page](https://huggingface.co/docs/transformers/index#supported-frameworks) has a dark mode font coloring issue. Dataframe titles are not visible. I am using chrome 103.0.5060.134 on manjaro linux if that helps. Stay safe 

![image](https://user-images.githubusercontent.com/74963545/190352043-64de03e9-d1b7-46f8-9faf-86c96e9b95be.png)

**Comment by krampstudio** [comment]
@osbm This should be fixed with the next deployment

**Comment by osbm** [comment]
Wow you guys are fast.
