### ISSUE TITLE
Feature request: add link to model documentation 

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/hub-docs#31]
**Is your feature request related to a problem? Please describe.**
As discussed on Slack, it would be nice if we add a direct link to the documentation of a model on the hub (e.g. linking to https://huggingface.co/transformers/model_doc/bert.html for [bert-base-uncased](https://huggingface.co/bert-base-uncased)). This can probably be done based on the `config.json` of a model.

**Describe the solution you'd like**
A button could be added either next to "Deploy" and "Use in Transformers", or a link could be added within the "Use in Transformers" button.

cc @julien-c

**Comment by osanseviero** [comment]
This is now solved at least for transformers
