### ISSUE TITLE
Documentation for TrainingArguments parameters not showing

### ISSUE THREAD

**Issue by erickrf** [huggingface/hub-docs#323]
The documentation for the [TrainingArguments constructor](https://huggingface.co/docs/transformers/main/en/main_classes/trainer#transformers.TrainingArguments) parameters is not being compiled. It seems I have to check the code for their description.

**Comment by osanseviero** [comment]
cc @sgugger @mishig25 on this topic

**Comment by osanseviero** [comment]
This now shows :D
