### ISSUE TITLE
Editing a TXT file. Result in a Python view???

### ISSUE THREAD

**Issue by sneedgers** [huggingface/hub-docs#336]
### Describe the bug

Edit a TXT file, it will show as a python code? 
which is funny 

### Reproduction

![image](https://user-images.githubusercontent.com/107140768/192823656-6fd20b06-ef88-4d79-b9d7-3ac6596e6225.png)
image is self explanetory lol 

### Logs

```shell
-
```

### System Info

```shell
-
```

**Comment by Wauplin** [comment]
I moved the issue to this repo as it is not `huggingface_hub` related.
@sneedgers you would prefer no linting at all I presume ?

**Comment by osanseviero** [comment]
There is an internal issue on this at https://github.com/huggingface/moon-landing/issues/3489 (cc @gary149 @beurkinger )

**Comment by sneedgers** [comment]
> There is an internal issue on this at https://github.com/huggingface/moon-landing/issues/3489 (cc @gary149 @beurkinger )

Its actually backend issue. because its an issue inside the docker! 
it was working fine !

**Comment by osanseviero** [comment]
This is fixed! :fire:
