### ISSUE TITLE
Allow for streamlit styling

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/hub-docs#345]
In streamlit, we can do some (very) basic styling through the [config](https://docs.streamlit.io/library/advanced-features/configuration#theming) system. In short, we can add a `.streamlit/config.toml` file to our app that contains colors and base themes.

From what I tested, this does not work on the HF Spaces on an app that _does_ display the styling locally. Tested with streamlit 1.10.0.

**Comment by osanseviero** [comment]
At the moment we don't support specifying a `config.toml`

Cc @cbensimon

**Comment by osanseviero** [comment]
This is now done afaik cc @whitphx
