### ISSUE TITLE
Image-to-Image Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#353]
This is the tracker for completion of task page for `image-to-image` task. The task page is here: https://huggingface.co/tasks/image-to-image You can contribute parts of a task or the whole task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to #369 if you want to contribute! 🤗 

List of items to contribute:
- [x] Task description
- [ ] Subtasks (if there is any)
- [x] Most used dataset for the task
- [x] Most used model for the task
- [x] Metrics that are used to evaluate the task
- [x] Libraries used for the task
- [x] Use cases
- [x] Small snippet for inference that demonstrates the task
- [x] Task Schema
- [x] Model for Widget

**Comment by Paul92** [comment]
Hello @merveenoyan. Would be happy to contribute to this task :).

**Comment by osmanalenbey** [comment]
@merveenoyan I will be happy to contribute :)

**Comment by merveenoyan** [comment]
@Seyda1 hello 👋 We made this task page for text classification task, this is the level of technicality we expect https://huggingface.co/tasks/text-classification. They are wikipedia-like pages rather than super technical documentation, you can even fix a grammar of an existing page if you're willing to contribute, or add information to a task you have expertise in (you don't necessarily need to know about a task that has an empty page but rather contribute to any of the pages)

**Comment by sazio** [comment]
Hey @merveenoyan, I'd be happy to help if there're any items left for contributions 🤗

**Comment by osmanalenbey** [comment]
#392 Added Image-to-Image 'Most Used Models for the Task'

**Comment by aneesh-aparajit** [comment]
Hello @merveenoyan, I'd be happy to contribute if there are components left to contribute!

**Comment by merveenoyan** [comment]
@aneesh-aparajit you can always contribute given these are wikipedia like pages 🙂 maybe take a look at here and see if there's anything you'd like to add? https://github.com/huggingface/hub-docs/tree/main/tasks/src/image-to-image

**Comment by merveenoyan** [comment]
@aneesh-aparajit currently a small snippet to infer with the task, libraries used and subtasks (task variants) are missing, would you like to contribute?

**Comment by aneesh-aparajit** [comment]
Yeah sure... just let me know what I'll have to do...

**Comment by merveenoyan** [comment]
@aneesh-aparajit you can contribute 🙂

**Comment by osanseviero** [comment]
This is now done, thanks a lot everyone! :fire:
