### ISSUE TITLE
Table-question-answering Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#358]
This is the tracker for completion of task page for `table-question-answering` task. The page is here: https://huggingface.co/tasks/table-question-answering. You can contribute parts of a task or the whole task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:
- [x] Task description
- [x] Subtasks (if there is any)
- [x] Most used dataset for the task
- [x] Most used model for the task
- [x] Metrics that are used to evaluate the task
- [x] Libraries used for the task
- [x] Use cases
- [x]  Small snippet for inference that demonstrates the task
- [x] Task Schema
- [x] Model for the Widget

**Comment by haotieu2001** [comment]
Hi Merve, I want to contribute to this task.

**Comment by congaco** [comment]
@merveenoyan @haotieu2001 hello are Libraries used for the task and  Subtasks (if there is any) still left? I would like to contribute to theses tasks

**Comment by merveenoyan** [comment]
@haotieu2001 you can 🙂 there's no open PR for this from what I see.
@congaco yes you can contribute them 🙂
