### ISSUE TITLE
Visual-question-answering Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#362]
This is the tracker for completion of task page for `visual-question-answering` task. The page is here: https://huggingface.co/tasks/visual-question-answering You can contribute parts of a task or the whole task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:

- [x] Task description
- [x] Subtasks (if there is any)
- [x] Most used dataset for the task
- [x] Most used model for the task
- [x] Useful Resources
- [x] Metrics that are used to evaluate the task
- [x] Libraries used for the task
- [x] Use cases
- [x] Small snippet for inference that demonstrates the task
- [x] Task schema
- [x] Model for the Widget

**Comment by jlondonob** [comment]
@merveenoyan I'd love to help with this!

**Comment by kushal-gopal** [comment]
Would like to contribute to the "Useful Resources" section.
@jlondonob Please let me know if it is overlapping with yours, thanks!

**Comment by Bharat123rox** [comment]
@jlondonob @kushal-gopal can I contribute to the task description, most used dataset and most used model for the task? There seems to be no overlap
cc @merveenoyan

**Comment by jlondonob** [comment]
@kushal-gopal sounds great! It does not overlap at all.

**Comment by jlondonob** [comment]
Hey @Bharat123rox, I filled those fields in #382. It would be great to get your feedback if you think they can be improved!

**Comment by merveenoyan** [comment]
@Bharat123rox you can contribute libraries used for the task, subtasks and useful resources 🙂
