### ISSUE TITLE
Text-to-Image Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#364]
This is the tracker for completion of task page for `text-to-image` task. The page is here: https://huggingface.co/tasks/text-to-image You can contribute parts of a task or the whole task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:

- [x] Task description
- [x] Subtasks (if there is any)
- [x] Most used dataset for the task
- [x] Most used model for the task
- [x] Metrics that are used to evaluate the task
- [x] Libraries used for the task
- [x] Use cases (you can still add more!)
- [x] Useful Resources (you can still add more!)
- [x] Small snippet for inference that demonstrates the task
- [x] Task Schema
- [x] Model for the Widget

**Comment by 02shanks** [comment]
Hi, @merveenoyan I would like to contribute to this task. I would like to start with the **Task description** and **Most used dataset for the task**

**Comment by oguzakif** [comment]
Hi, @merveenoyan  I would like to contribute to this task. I can start with "Most used model for the task" and "libraries used for the task".

**Comment by ishandutta0098** [comment]
Hi @merveenoyan , I would like to contribute to the entire task starting from the Task Description. Do I need to submit a pull request after fulfilling all the contribution items or I can raise a pull request for one item at a time as well?

**Comment by samyak1999** [comment]
Hi @merveenoyan I would like to contribute to to this task .I am opting to contribute in "Most used dataset for the task",
"Most used model for the task", "Metrics that are used to evaluate the task" ,"Libraries used for the task" and 
"Use cases"

**Comment by samyak1999** [comment]
@merveenoyan text-to-image folder is not present under 'tasks/src'

**Comment by samyak1999** [comment]
Can we provide link to the dataset that's used for text-to-image?

**Comment by merveenoyan** [comment]
@samyak1999 apparently @oguzakif has provided dataset and model, and @ishandutta0098 has provided use cases and useful resources. Can you check if your additions overlap with them before adding your contributions? 🙂

**Comment by samyak1999** [comment]
@merveenoyan I will look into it and would make sure the contents don't overlap

**Comment by AshiqAbdulkhader** [comment]
@merveenoyan I would like to contribute
