### ISSUE TITLE
Tasks Documentation Sprint 🎃

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#369]
Welcome to Tasks sprint! This is a documentation sprint aimed to onboard machine learning practitioners to open-source. 🤗
Task pages are documentation effort to lower the barrier for building ML products. There are pages for most used tasks, and some of the pages are empty that need contribution. You can help us fill them. 🥺 The ones with "contribute 🖐" sign are empty. You don't need to be an expert to contribute to these pages, think of them as wikipedia-like pages for every task.

![Ekran Resmi 2022-10-06 10 59 26](https://user-images.githubusercontent.com/53175384/194314817-9d1f4efb-3675-4acc-951c-8d8d01a306ab.png)

An example task page includes basic information about a machine learning task, see an example [here](https://huggingface.co/tasks/text-classification). 🙂

We have prepared two guides for you to get started with sprint:
- [GitHub Contribution Guide](https://huggingface2.notion.site/Contribution-Guide-19411c29298644df8e9656af45a7686d) (it is _the_ guide if you've never contributed to an open-source project)
- [Task Contribution Guide](https://github.com/huggingface/hub-docs/blob/main/tasks-contribution-guide.md) (this is the one that includes guidelines around documentation)

We can contribute one part about a task (or multiple or the whole task 🤯) and when the task page is complete, we will put it on hf.co/tasks. 
The steps are simple: 
1. Find the task you're interested in, in the issues. 
(an example)
![Ekran Resmi 2022-10-06 14 38 04](https://user-images.githubusercontent.com/53175384/194314459-ccd753e0-3dea-4eb1-b437-0296bda68e98.png)
2. Ping us in the task's issue, saying you're interested. 
3. Open the pull request as instructed in the GitHub contribution guide.
We will review and help you out in the process. 🤗 ❤️

**Comment by Bharat123rox** [comment]
Interested! Can this be considered for Hacktoberfest too?

**Comment by osanseviero** [comment]
This is for sure considered for Hacktoberfest!

**Comment by Gerard-170** [comment]
Hi @merveenoyan can i work on 'Voice Activity Detection' task page? I have seen that is not added as issue, please let me know how can i proceed. :)

**Comment by merveenoyan** [comment]
@Gerard-170 I think it's because we don't really have a model on it atm. if you want to contribute audio tasks I will come up with missing items from them and let you know, does this work? I will also add couple of sections that can be contributed to other tasks that are already done too!

**Comment by Gerard-170** [comment]
Hi @merveenoyan yeah it works for me, also i will take a look at other tasks if there's some sections missed👍

**Comment by merveenoyan** [comment]
@Gerard-170 above you can find new task pages to be contributed 🙂

**Comment by merveenoyan** [comment]
Thanks a lot everyone for all the contributions! It's only Image-to-Text task that is left not contributed (about.md part) would anyone be up?

**Comment by merveenoyan** [comment]
@NA424 yes!

**Comment by NA424** [comment]
Cool.
Can you share some references to do so?
I'm new in the community.

--
Thanks and Regards,
Suraj Dengale,
Graduate Research Students,
Vision Science Lab,
Department of Electrical Engineering,
National Tsing Hua University,
Hsinchu, Taiwan (R.OC)

**Comment by merveenoyan** [comment]
@NA424 the references exist in this issue (you can take a look at the first post 😊 )
