### ISSUE TITLE
Cannot see table header in dark mode

### ISSUE THREAD

**Issue by Muennighoff** [huggingface/hub-docs#393]
### Describe the bug

See the image, the header should say Model & Parameters, but is just black. Hope this is the right place to report the bug 🙂

<img width="810" alt="Screenshot 2022-10-11 at 17 17 46" src="https://user-images.githubusercontent.com/62820084/195131762-03c0b450-2902-4fd6-ad71-8dce608c9655.png">

### System Info

```shell
Chrome Version 105.0.5195.125 (Official Build) (x86_64)
```

**Comment by Wauplin** [comment]
I transferred the issue as this is not related to the library `huggingface_hub` but to the interface itself.

**Comment by osanseviero** [comment]
cc @gary149 @beurkinger

**Comment by gary149** [comment]
Thanks for notifying. @krampstudio is working on it and it should be fixed very soon!

**Comment by Pierrci** [comment]
This was closed internally by #3920 @krampstudio, correct?

**Comment by krampstudio** [comment]
Yes, it's now fixed 
![image](https://user-images.githubusercontent.com/468620/195647266-819878a2-c430-49fd-bef6-5c75a47b6521.png)
