### ISSUE TITLE
Audio Classification Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#406]
This is the tracker for completion of task page for audio-classification task. The page is here: https://huggingface.co/tasks/audio-classification You can contribute parts of a task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:
- [x] Subtasks
- [x] Use cases
- [x] Useful Resources
- [x] (or any other thing you'd like to add)

**Comment by akashAD98** [comment]
@merveenoyan can i contribute here

**Comment by merveenoyan** [comment]
@akashAD98 yep! what do you mean with need to add this additional 4 task?

**Comment by osanseviero** [comment]
Should this issue be closed? https://huggingface.co/tasks/audio-classification is already complete and has the sections mentioned
