### ISSUE TITLE
Automatic-speech-recognition Task Page

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#408]
This is the tracker for completion of task page for automatic-speech-recognition task. The page is here: https://huggingface.co/tasks/automatic-speech-recognition You can contribute parts of a task! (There's no single assignee to a task, these are wikipedia-like pages)
You can refer to https://github.com/huggingface/hub-docs/issues/369 if you want to contribute! 🤗

List of items to contribute:
- [x] Subtasks
- [x] Use cases
- [x] Useful Resources
- [x] (or any other thing you'd like to add)

**Comment by Gerard-170** [comment]
Hi, I will contribute with Substasks and Use cases, If I come up with something new, I will add it. :D

**Comment by Gerard-170** [comment]
Hi @merveenoyan I have a question regarding to Subtasks section, Is this similar to Task Variants?

**Comment by merveenoyan** [comment]
@Gerard-170 yup!
