### ISSUE TITLE
Duplicate task type in `Types.ts`: `tabular-to-text` and `table-to-text`

### ISSUE THREAD

**Issue by julien-c** [huggingface/hub-docs#429]
Which one is the correct one?

https://github.com/huggingface/hub-docs/blob/8d58c1b786e62890fd990c2ce2a5e25b1be786e6/js/src/lib/interfaces/Types.ts#L493-L516

**Comment by osanseviero** [comment]
I think `table-to-text` is for tasks such as Table Question Answering which is different from tabular to text

**Comment by julien-c** [comment]
hmm ok but they both have `rdf-to-text` as a subtask (and both are blue)

a subtask should only be inside one task no?

**Comment by merveenoyan** [comment]
@osanseviero there's a separate id for `table-question-answering` no? 
BTW I decided to not included this task in tasks given there's no model as of now. @julien-c WDYT

**Comment by osanseviero** [comment]
`rdf-to-text` should only be in `tabular-to-text` as per https://docs.google.com/document/d/1wTOa3s23T7dsAC14AQYWP1oqgBwgrp2V4zrJmDDF_Hc/edit#heading=h.ysfmqr43vng0

But I also think `table-to-text` might be confusing. @lhoestq what was the use case of this task?

**Comment by lhoestq** [comment]
tabular to text = one row of a table to text

table to text = one full table to text

**Comment by merveenoyan** [comment]
Why don't we have them both in same abstraction, what is the difference? table with one row is still a table no? 😅 does a model know whether it should look in one row or not?

**Comment by osanseviero** [comment]
I think the point is that in table-to-text, the input is a full table and the output is a single string. In tabular-to-text, the input is a full table, but for each row you get a string.
