### ISSUE TITLE
[FEATURE REQUEST] Easier mentioning of @username in the community tab

### ISSUE THREAD

**Issue by cakiki** [huggingface/hub-docs#454]
Right now the autocomplete of usernames seems to load every single user on the hub and users have to have the correct spelling. It might be better to first try to load people **1.** a user normally mentions and **2.** people who have already contributed to the thread I'm currently in.

**Comment by julien-c** [comment]
[internal issue](https://github.com/huggingface/moon-landing/issues/3496)

**Comment by cakiki** [comment]
https://twitter.com/lizallendorf/status/1590432089677402112  ❤️

**Comment by julien-c** [comment]
thanks @allendorf :)
