### ISSUE TITLE
git lfs tracking "*.ckpt" files with default .gitattributes

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#470]
I keep forgetting `git lfs track "*.ckpt"` 🤪 if it is possible please add "*.ckpt" in default .gitattributes

**Comment by julien-c** [comment]
Yes! supportive

**Comment by julien-c** [comment]
@Wauplin want to tackle this? should be easy to do it in `moon-landing`

**Comment by Wauplin** [comment]
Sure ! :)

**Comment by camenduru** [comment]
thanks ❤

**Comment by Pierrci** [comment]
should be live in the next 24 hours
