### ISSUE TITLE
Bug with licenses table

### ISSUE THREAD

**Issue by coyotte508** [huggingface/hub-docs#478]
https://huggingface.co/docs/hub/repositories-licenses

![image](https://user-images.githubusercontent.com/342922/200140558-6ce43e1f-d477-4a46-958f-643866bcd7a1.png)

It should be a table

**Comment by julien-c** [comment]
😱 😱

**Comment by julien-c** [comment]
Proposed fix in #479 and https://github.com/huggingface/moon-landing/pull/4406
