### ISSUE TITLE
Model card for distilbert-base-cased has a wrong distillation process link

### ISSUE THREAD

**Issue by Bearnardd** [huggingface/hub-docs#480]
## Describe the bug
Link for the code for the distillation process in [distilbert-base-uncased](https://huggingface.co/distilbert-base-cased) is incorrect. The  link is updated for the [distilbert-base-uncased](https://huggingface.co/distilbert-base-uncased).

## Solution
Update link `https://github.com/huggingface/transformers/tree/main/examples/distillation` => `https://github.com/huggingface/transformers/tree/main/examples/research_projects/distillation`

@sgugger

**Comment by julien-c** [comment]
Hi @Bearnardd – good catch, any way you could open a PR directly on the model repo on huggingface hub? (look for the "community tab" or just "edit model card")

Thanks!

**Comment by Bearnardd** [comment]
> Hi @Bearnardd – good catch, any way you could open a PR directly on the model repo on huggingface hub? (look for the "community tab" or just "edit model card")
> 
> Thanks!
Hi @julien-c! Sure, I am gonna open a PR in the evening.

**Comment by Bearnardd** [comment]
PR: https://huggingface.co/distilbert-base-cased/discussions/2

**Comment by Bearnardd** [comment]
Fix was merged
