### ISSUE TITLE
Questions for search engines.

### ISSUE THREAD

**Issue by ganzhiruyi** [huggingface/hub-docs#481]
**Is your feature request related to a problem? Please describe.**
Huggingface is a good platform for sharing models. I have a question about the search engine. I have upload my stable-diffusion models recently, you can find from https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1.
However, when I choose Chinese tag, type 'stable diffusion', I can't find my model. I can find my model when I choose Chinese tag, type 'stable-diffusion', I want to know why and how to optimize it.
Thanks!

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/4384420/200490556-271d659b-752b-49da-9ffd-8f7209f9702c.png">

<img width="1097" alt="wecom-temp-fdc2e5adb637092cc0b50e9e8a04a4ba" src="https://user-images.githubusercontent.com/4384420/200482805-572f760f-c6a7-4feb-a212-185f7d5c32b3.png">

**Comment by osanseviero** [comment]
Search has improved since this issue was opened. https://huggingface.co/IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1 does show upon same search conditions :rocket:
