### ISSUE TITLE
Organization cards cannot render most markdown and html correctly

### ISSUE THREAD

**Issue by Lauler** [huggingface/hub-docs#509]
**Is your feature request related to a problem? Please describe.**
Organization cards on an organization's frontpage on huggingface.co appear to be very limited in the markdown and html that they are able to render. As an example: it cannot handle nor display lists.

Here is an example of our organization's front page: https://huggingface.co/KBLab
Here is how the README used to generate the front page is rendered in isolation: https://huggingface.co/spaces/KBLab/README

The front page has problems rendering markdown and html and does not behave like a majority of users would expect. Especially since the documentation for organization cards claims that [both markdown and plain html can be used](https://huggingface.co/docs/hub/organizations-cards) in the organization card README.

**Describe the solution you'd like**
Organization cards should be able to display markdown and html the same way model cards can.

**Comment by osanseviero** [comment]
cc @gary149 @beurkinger @julien-c

**Comment by coyotte508** [comment]
Hi @Lauler 

We recently released a fix (thanks @Kakulukian !). Can you check if it's ok now?

**Comment by Lauler** [comment]
The lists and and layout look as expected now. Seems to render markdown the same as model cards. Thanks for the quick fix!

@coyotte508 The one functionality that may have been lost in the fix seems to be the ability to customize link colors with HTML. However, it also looks like you have removed that example from the documentation of organization cards, so perhaps it's working as intended? Custom coloring is not a must-have, but a nice-to-have.

The issue can be closed if that part is working as intended! Thanks again for the fix.

**Comment by coyotte508** [comment]
@Lauler you may need to add `!important` to the CSS styles.

Example card: https://huggingface.co/TestSSRF

```markdown
---
title: README
emoji: 👀
colorFrom: indigo
colorTo: indigo
sdk: static
pinned: false
---

Edit this `README.md` markdown file to author your organization card 🔥


This is a [link](https://huggingface.co)

below is some style to change link colors to red

<style>
a {
  color: red !important;
}
</style>
```
