### ISSUE TITLE
How to stop noisy warning on svelte-check

### ISSUE THREAD

**Issue by mishig25** [huggingface/hub-docs#516]
Currently, [npm run check](https://github.com/huggingface/hub-docs/blob/08666aa07b39f00f51e9c182e3672c8207153b0b/js/package.json#L8) outputs a lot of warnings that say:
```
Warn: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer (svelte)
```

for example [here](https://github.com/huggingface/hub-docs/actions/runs/3492276947/jobs/5845878964#step:6:960)

because there are so many warnings, it is hard to see actual errors.
Any idea how to fix it ? 
cc: @coyotte508 @Pierrci @beurkinger

**Comment by coyotte508** [comment]
fix all warnings & fail on warnings as well!

**Comment by beurkinger** [comment]
https://github.com/parcel-bundler/parcel/issues/8005 looks like it could be an issue with terse ?

**Comment by beurkinger** [comment]
orrr a Node issue 
https://github.com/mozilla/source-map/issues/454
https://github.com/gatsbyjs/gatsby/issues/35607
https://github.com/mozilla/source-map/issues/432

**Comment by beurkinger** [comment]
hmm it seems the warnings are not present anymore ? Should we close this issue, or did I miss something @mishig25  ?
https://github.com/huggingface/moon-landing/pull/4797/checks
