### ISSUE TITLE
Tracking integration for Zero-Shot Sequence Labeling with TARS [FLAIR]

### ISSUE THREAD

**Issue by lewtun** [huggingface/hub-docs#52]
In[ v0.9](https://github.com/flairNLP/flair/releases/tag/v0.9) of `flair` a new zero-shot sequence labeling feature was included which seems (a) very exciting and (b) very useful for real-world NER applications where acquiring labeled data is expensive.

It would be cool to include support for this in the Hugging Face Hub, possibly as a companion widget to the existing [one](https://huggingface.co/joeddav/xlm-roberta-large-xnli) for zero-shot classification.

Here's a [link](https://kishaloyhalder.github.io/pdfs/tars_coling2020.pdf) to the paper behind the TARS technique.

cc @osanseviero 

- [ ] Integration with Inference API. Select at least one of the following:
  - [ ] Added a `transformers` `pipeline`
  - [ ] Added to Community Inference API for 3rd party library
  - [ ] Added to Community Inference API for generic
- [ ] Added basic UI elements (icon, order specification, etc)
- [ ] Added a widget

**Comment by osanseviero** [comment]
GIving it's been 2 years and we've had no further requests for this nor more models, I will close it.
