### ISSUE TITLE
Improve documentation about Spaces Upgrades pricing

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#523]
@christophe-rannou would you be able to take this one?

**Comment by christophe-rannou** [comment]
Sure thing, what kind of information you're expecting ? Mainly during which stage a space is actually billed ?

Should I have this under the Other -> Billing section or under Spaces -> Spaces GPU Upgrades ?

**Comment by osanseviero** [comment]
* Yes, documenting that we bill for stages X and Y, bill for minute running, etc. How to turn off might be good as well
* I think this could live somewhere near https://huggingface.co/docs/hub/spaces-gpus, maybe as a separate page or as a subsection of the page

**Comment by julien-c** [comment]
nice!
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/326577/205649543-3c923ad9-d047-4e0f-8552-c6fac8688132.png">
