### ISSUE TITLE
Some Bugs found on the `Bettertransformer` tutorial page

### ISSUE THREAD

**Issue by ravenouse** [huggingface/hub-docs#528]
I found some dead links and some unclear points on this tutorial [webpage](https://huggingface.co/docs/optimum/bettertransformer/tutorials/contribute). 

1. In `Step 2: Building the xxxLayerBetterTransformer module`, the link to `modeling_encoder.py ` is dead. 

2. In `Step 4: Sanity check!`, the link to ` tutorials sections` is dead.

3. The description about what conditions the `BetterTransformer` are not applied is unclear and kinda confusing, particularly for the even head condition. On this tutorial, it seems that the model should have an even number of head to be convertible, while on this [notebook](https://colab.research.google.com/drive/1Lv2RCG_AT6bZNdlL1oDDNNiwBBuirwI-?usp=sharing#scrollTo=wwgK2FPzC239), the even head seems to prevent the model to be converted.

Could you help to solve these problems?

Thank you so much.

@younesbelkada

**Comment by younesbelkada** [comment]
Hi @ravenouse , 
Thank you very much for your issue! 
I made a PR on `optimum` to fix the dead link: https://github.com/huggingface/optimum/pull/517
Could you move the issue on [`optimum`]( https://github.com/huggingface/optimum ) instead for the thrid point? Thanks!
