### ISSUE TITLE
Ability to remove profile picture

### ISSUE THREAD

**Issue by vilimus** [huggingface/hub-docs#539]
**Is your feature request related to a problem? Please describe.**
Once a profile picture is uploaded, it cannot be removed.

**Describe the solution you'd like**
Add the ability to remove one's profile picture and revert to the Hugging Face default gradient color picture.

**Describe alternatives you've considered**
None.

**Additional context**
GitHub has a similar feature. When Edit profile picture is clicked, two options are presented: "Upload a photo..." and "Remove photo"

**Comment by osanseviero** [comment]
cc @gary149

**Comment by osanseviero** [comment]
This is now possible! :fire:
