### ISSUE TITLE
Please also stream all youtube live events in twitch too

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#553]
I think this is official twitch channel https://www.twitch.tv/huggingface please stream also here 
you can use this https://restream.io for multistream. I always miss live events 😥

**Comment by osanseviero** [comment]
You can check out https://www.twitch.tv/HuggingFace where we'll do the live stream of today's event. Usually very few people join in twitch (2-3 people) so that's why we stopped streaming it over there

**Comment by camenduru** [comment]
@osanseviero thanks ❤ please also enable the vods in twitch https://help.twitch.tv/s/article/video-on-demand?language=en_US

**Comment by osanseviero** [comment]
We do this but, see https://www.twitch.tv/huggingface/videos. But it seems that streams are deleted after 7 days.

**Comment by camenduru** [comment]
hi @osanseviero 👋 highlights are saved indefinitely 
https://help.twitch.tv/s/article/creating-highlights-and-stream-markers?language=en_US 
set start = start of the video and end = end of the video  🎉

**Comment by osanseviero** [comment]
Cool! TIL about this :fire: Just added, the highlights are processing now but should be available later
