### ISSUE TITLE
Hub docs improvements

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#563]
Some undocumented features

- [x] Report repos
- [x]  In https://huggingface.co/docs/hub/index, some Spaces sections are missing
- [x] Duplicating a Space is outdated https://huggingface.co/docs/hub/spaces-more-ways-to-create#duplicating-a-space
- [ ]  Link to https://huggingface.co/docs/datasets-server/parquet from somewhere in datasets section
- [x] Deploy to Spaces option
- [ ] Mention inference API is automatically disabled for invalid repos
- [ ] Accessing all comments history

**Comment by julien-c** [comment]
- Deploy to Spaces i've done it yesterday a bit in https://github.com/huggingface/hub-docs/pull/562


I agree with everything else you list

**Comment by osanseviero** [comment]
Some docs I think are missing

- [ ] Search? (e.g. full text search)
- [ ] [Spaces] Run with Docker
- [ ] [Spaces] New clone repository button
- [ ] [Discussions] Pinning discussions
- [ ] [Discussions] Disable Discussions and PRs
- [ ] [Models & Datasets] Model card metadata UI
- [ ] [Models] Deploy on Spaces
- [ ] [Models] Total Downloads
- [ ] [User Settings] Not for all audiences

**Comment by Michellehbn** [comment]
Spaces: https://github.com/huggingface/spaces-app-manager/issues/887

**Comment by Michellehbn** [comment]
Search: https://github.com/huggingface/hub-docs/pull/842

**Comment by krampstudio** [comment]
For discussions, I started https://github.com/huggingface/hub-docs/pull/844

**Comment by severo** [comment]
For 

>  Link to https://huggingface.co/docs/datasets-server/parquet from somewhere in datasets section

we now have https://huggingface.co/docs/hub/datasets-viewer#access-the-parquet-files

Wdyt?

**Comment by Michellehbn** [comment]
https://github.com/huggingface/hub-docs/pull/928 for (Models) Deploy on Spaces

**Comment by Michellehbn** [comment]
Hi @osanseviero ! So most of these doc updates are covered, I had just done one for Deploy on Spaces however there is already one at https://huggingface.co/docs/hub/spaces-more-ways-to-create (thanks @julien-c) Please let me know if there are any new requests on doc updates or if we can go ahead and close! Thanks!

**Comment by julien-c** [comment]
personally for now i'd rather have Spaces under the Hub , but let's see what others think!
