### ISSUE TITLE
please increase docker rate limits

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#568]
`ERROR: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

https://www.docker.com/increase-rate-limits/

To increase your pull rate limits you can upgrade your account to a [Docker Pro or Team subscription](https://www.docker.com/pricing).   please tell me you subscribed :yum:

**Comment by camenduru** [comment]
I can't communicate with docker websocket
I can't give permission to user to write file on server

**Comment by osanseviero** [comment]
This is fixed now
