### ISSUE TITLE
Add resources to Depth Estimation task page

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/hub-docs#571]
We now have the NYU Depth V2 dataset: https://huggingface.co/datasets/sayakpaul/nyu_depth_v2. We're in communication with the dataset author to transfer the dataset from my account to an appropriate org. 

We're also working on a depth estimation fine-tuning tutorial: https://github.com/huggingface/notebooks/pull/264

Once the above two things are done, we should update the resources of the [depth estimation task page](https://huggingface.co/tasks/depth-estimation) to reflect them. 

Cc: @osanseviero @merveenoyan @nateraw

**Comment by merveenoyan** [comment]
Closing this since the task page is complete :)

**Comment by darwinharianto** [comment]
Will the depth estimation fine tuning tutorial be added to the task page?
