### ISSUE TITLE
git ssh signing 

### ISSUE THREAD

**Issue by wallies** [huggingface/hub-docs#583]
**Is your feature request related to a problem? Please describe.**
GPG key git signing can offer be a large hurdle for many. Github has now introduced the capability to use your ssh key to sign commits. Would be good if huggingface could support this.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by julien-c** [comment]
Yes! it's been requested before and we might look into this at some point

**Comment by osanseviero** [comment]
This is released now! 🔥
