### ISSUE TITLE
Auto spam detection and ability to report people and organizations

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#591]
Bad news, ☹ spammers have found 🤗 and I have been getting spam every day. 😭 this will become a big and big problem. 
Kaggle has a super simple spam prevention system you can not open same tittle more then 3 times anywhere in Kaggle, this is not a solution but something hehe and no report button 🚔

![Screenshot 2023-01-04 090058](https://user-images.githubusercontent.com/54370274/210493651-63542c34-37b6-4953-999c-d19ba8cc5547.jpg)

![Screenshot 2023-01-04 085313](https://user-images.githubusercontent.com/54370274/210492788-744b07c6-42c6-487d-b282-e5760d9a637a.jpg)

Apparently spamming YouTube tutorial videos allowed in 🤗 I don't know why.  How about we create a space where people can spam their YouTube tutorial videos to 🤗 one click spammer! write your YouTube video link and it spams every single community discussions 🎉 spammers love it 🤪

![Screenshot 2023-01-02 053153x](https://user-images.githubusercontent.com/54370274/210494431-a24c98f7-a9be-41e4-b49a-5f482ab9110a.jpg)

**Comment by julien-c** [comment]
cc @gary149 @osanseviero
