### ISSUE TITLE
New object detection and image segmentation widgets

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/hub-docs#6]
For the [DETR](https://arxiv.org/abs/2005.12872) model, which will soon be part of HuggingFace Transformers (see https://github.com/huggingface/transformers/pull/11653#issue-637061171), it would be cool to have object detection and image segmentation (actually panoptic segmentation) inference widgets.

Similar to the image classification widget, a user should be able to upload/drag an image to the widget, which is then annotated with bounding boxes and classes (in case of object detection), or turned into a segmentation map (in case of panoptic segmentation). 

Here are 2 notebooks which illustrate what you can do with the head models of DETR:

`DetrForObjectDetection`: https://colab.research.google.com/drive/170dlGN5s37uaYO32XKUHfPklGS8oB059?usp=sharing
`DetrForSegmentation`: https://colab.research.google.com/drive/1hTGTPGBLPRY1QkLmG7P9air6v04tcXUL?usp=sharing

The models are already on the hub: https://huggingface.co/models?search=facebook/detr

cc @LysandreJik

**Comment by osanseviero** [comment]
Since this pipelines and widgets are merged, I'll close this issue
