### ISSUE TITLE
Runtime error - Local hub-docs Preview

### ISSUE THREAD

**Issue by akshay-babbar** [huggingface/hub-docs#602]
After running this `doc-builder preview hub {my_path}/hub-docs/docs/hub/ --not_python_module`. I am getting this error 
```
RuntimeError: The following files are not present in the table of contents:
- model-cards-user-studies
- model-card-appendix
Add them to {my_path}/hub-docs/docs/hub/_toctree.yml.
```
I am trying to run this project locally to add some documentation. Can anyone please help?

**Comment by osanseviero** [comment]
You also need to use `disable_toc_check` for this to run, https://github.com/huggingface/hub-docs/blob/main/docs/hub/_config.py#L1

**Comment by akshay-babbar** [comment]
Sorry, but how to use this @osanseviero?, asking since `disable_toc_check` and in the config file it is already set to True & cannot be used as an optional arg with `doc-builder preview`

**Comment by osanseviero** [comment]
Just to confirm, did you install `doc-builder` from source code recently? (maybe you have an older version)

**Comment by akshay-babbar** [comment]
Yes it did work now since i installed it from source, thanks. But one final thing, my final aim was to generate documentation inside `hub-docs/tasks` so that the changes i make there i can preview them before i create a PR. Can you give a solution there too?
