### ISSUE TITLE
May I receive mail when the space is built?

### ISSUE THREAD

**Issue by camenduru** [huggingface/hub-docs#606]
📲 💌 🛰️ ⌛️

**Comment by camenduru** [comment]
I found a way to notify myself with ifttt.com webhook but still I want 🤗 implementation 😋

**Comment by osanseviero** [comment]
We're releasing Hub webhooks very soon, which would enable this kind of use case :)

**Comment by camenduru** [comment]
woohoo this is cool `down notification` mail thanks ❤

![Screenshot 2023-01-24 040957](https://user-images.githubusercontent.com/54370274/214192834-6ba020b6-cacc-4ebe-b204-7d923413d017.jpg)
