### ISSUE TITLE
Improve responsiveness of the docs.

### ISSUE THREAD

**Issue by y1450** [huggingface/hub-docs#615]
Currently, I believe the website does scale with screen. Ideally it would be nice, if the website is responsive.

Also, An option to toggle the sidebar would be QOL change for reader.

![transformer_docs](https://user-images.githubusercontent.com/107429941/212522654-f9fce6b8-612d-499f-84c2-aa4594aadcf7.gif)

**Comment by gary149** [comment]
> Currently, I believe the website does scale with screen. Ideally it would be nice, if the website is responsive.

Hi, not sure I understand correctly what's the expected behavior here? The documentation should already be responsive (working on mobile, tablet and desktop)

**Comment by y1450** [comment]
There is no such expected behavior in this case although it is an UX problem and maybe responsive is not the correct word to describe it.

For context, I work on a vertical monitor, often zoom in to read the pages. Ideally I would like the text to be a single column which would allow better reading experience.

Also taking Deep RL course and the reading experience on the website is not so pleasant. 
Here is how it look at 150% zoom
![image](https://user-images.githubusercontent.com/107429941/212687154-960a1c2e-585e-4127-a28c-3603f112d56d.png)

**Comment by krampstudio** [comment]
@y1450 thanks for reporting, but I'm not able to reproduce the mentioned issue:  zooming seems to work as expected:

![Peek 28-02-2023 14-23](https://user-images.githubusercontent.com/468620/221867184-715395c6-f7d5-4c01-84e5-ed0b50ed2387.gif)

Do you mind sharing more details:
 - browser / OS 
 - screen size, resolution & viewport (you can get the values from https://whatismyviewport.com/ )
 - anything in particular that could explain it? font scaling, accessibility plugin, etc.

**Comment by osanseviero** [comment]
As there has been no reply, I'll mark this as closed. Please feel free to re-open if you can still face the issue
