### ISSUE TITLE
Text regression rather than classification

### ISSUE THREAD

**Issue by ck37** [huggingface/hub-docs#65]
**Is your feature request related to a problem? Please describe.**
I am trying to share our hate speech measurement model, which predicts a continuous measure for hate speech severity. So it is doing text regression rather than classification, but the input remains just a text input that gets tokenized. Is it possible to clarify if I need to create a custom pipeline for this, or how else to proceed? I have one of our models uploaded for TF at https://huggingface.co/ucberkeley-dlab/hate-measure-roberta-large

The architecture is just a Transformer backbone, 1D global average pooling layer, followed by a linear output node.

**Describe the solution you'd like**
I would like to support the hosted inference API so that individuals can get a continuous score prediction out of our model and for the demo widget to work.

**Describe alternatives you've considered**
I'm not clear if I need to create a new TextRegression task for HuggingFace, which feels like it would be a large lift, or if there is an easier way to do this.

**Additional context**
The preprint for our work is at https://arxiv.org/abs/2009.10277 and this is to allow the model to be used in the Jigsaw Toxic Severity Kaggle competition: https://www.kaggle.com/c/jigsaw-toxic-severity-rating/overview

**Comment by osanseviero** [comment]
Copy-pasting from tagged issue

> Text regression is a special case of text classification. Hence the existing classes for text classification are sufficient to train and do predictions for regression problems. As @mapmeld described, the right way to train a regression model is by passing num_labels=1 to the AutoModelForSequenceClassification.from_pretrained method.

> Coming to the pipeline for inferencing, it can be easily created like this
pipe = pipeline('text-classification', model=trained_model_dir, function_to_apply="none")

> Remember to set the value of the parameter function_to_apply as "none" and not None.

So the tooling is already in place for this
