### ISSUE TITLE
Change Password Button Does Not work

### ISSUE THREAD

**Issue by Dimiftb** [huggingface/hub-docs#67]
Hi there, 

I've been trying reset my password, however the change password button doesn't work so I cannot submit the request. 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/26279721/159135805-7b79ab2f-aea3-459d-bd23-be37111243dd.png">

I've tried different browsers (Chrome, Safari), however I get the same issue. I also tried by pressing enter, however nothing happens. I'm sorry if this is not the right place to submit this issue, I wasn't sure where else.

**Comment by osanseviero** [comment]
Thanks for reporting, this is the right place. We'll look into this.

**Comment by osanseviero** [comment]
cc @Pierrci @gary149

**Comment by osanseviero** [comment]
This is fixed now :smile:

**Comment by Pierrci** [comment]
Hi @rooa, I just checked and I correctly received an email to reset my password. The main possibility I see here is that you're using a different email than the one set in your account.

**Comment by rooa** [comment]
Thanks @Pierrci for the suggestion. Indeed, that was the case. I didn't realize I changed my primary email address for authentication. Thank you very much for your help!
