### ISSUE TITLE
Doc search modal doesn't close on Esc

### ISSUE THREAD

**Issue by severo** [huggingface/hub-docs#730]
The doc search modal doesn't close on Esc key press, saving if it's the first keypress (nothing has been written in the search box)

Tested on:
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
- Chromium Version 114.0.5686.0

https://user-images.githubusercontent.com/1676121/229082641-60a6c7be-d4b9-4d2b-ab0b-2e411e83b5ca.mov

**Comment by osanseviero** [comment]
fyi @mishig25

**Comment by osanseviero** [comment]
Do you still face this issue @severo ?

**Comment by severo** [comment]
https://github.com/huggingface/hub-docs/assets/1676121/2d9d0e00-3bd9-42e1-a774-8b5ff663e7fd
