### ISSUE TITLE
Add a code snippet for image-to-text

### ISSUE THREAD

**Issue by osanseviero** [huggingface/hub-docs#735]
Example repo: https://huggingface.co/Salesforce/blip-image-captioning-base 

We should also add it in https://huggingface.co/docs/api-inference/detailed_parameters

**Comment by regstuff** [comment]
If it's not too much trouble, I'd suggest adding an example for each of the tasks here: https://huggingface.co/models
Right now I'd say bout 30% of the tasks are not detailed in the api-inference page.
HF ecosystem is pretty diverse and every task seems to have different params to consider. Examples in the API would be very helpful.
Thanks

**Comment by osanseviero** [comment]
Same for document understanding

**Comment by key88sf** [comment]
@osanseviero Also some details about how to deploy these image-to-text inference models on AWS Sagemaker (e.g. what "Task" do we select) ?

**Comment by KindaCallam-io** [comment]
Hey is there any update on this? 
Has anybody been able to get this working and potentially provide me with an example?

**Comment by xianbaoqian** [comment]
Thanks for fixing the PR! Verified that this config is working. CodeSpace can create pull request to hub-docs and run the server. We can close it now.

Proof: https://github.com/huggingface/hub-docs/pull/876
