### ISSUE TITLE
Wrong "use in Transformers" wigdet for models with remote code

### ISSUE THREAD

**Issue by sgugger** [huggingface/hub-docs#752]
As seen in [this model](https://huggingface.co/mosaicml/mpt-1b-redpajama-200b), the widget that shows how to use the model in Transformers has some wrong code. This seems to be the case for any model with remote code.

For those models, the architecture field will show the name the user picked for their model and should probably be replaced by what can be found in the `auto_map` key of the config, which will contain the right auto class. Additionally, `trust_remote_code=True` should be added in the snippet of code (otherwise an exception will be raised by Transformers).

**Comment by osanseviero** [comment]
This is fixed now
