### ISSUE TITLE
Sign up API seems to be down

### ISSUE THREAD

**Issue by jakelucasnyc** [huggingface/hub-docs#775]
I'm attempting to sign up for a huggingface account and, during the sign-in process, this is what the web interface returned after 20-30 seconds of stalling without a sign that the signup form submittal occurred:

<img width="1440" alt="image" src="https://github.com/huggingface/hub-docs/assets/70170165/7572c647-0f47-4b6b-a3c8-5aa08b89ad87">

Steps to reproduce:
- Fill in a valid email address and password into the form
- Press enter or manually press the "Next" button
- Wait until the console is updated (took 20-30 seconds on my internet connection)

As a result, I'm unable to create an account.

**Comment by jakelucasnyc** [comment]
To clarify, this is not an internet connectivity issue. Other websites load very quickly

**Comment by julien-c** [comment]
we had some [intermittent backend trouble today](https://www.linkedin.com/posts/julienchaumond_post-mortem-through-a-combination-of-human-activity-7061769278953279488-yeU-?utm_source=share&utm_medium=member_desktop), it's possible this was related
