### ISSUE TITLE
Model downloads not being counted

### ISSUE THREAD

**Issue by ricardorei** [huggingface/hub-docs#776]
### Describe the bug

The download counts for the models under Unbabel Org don't seem to be working.

E.g: 

[Unbabel/wmt22-comet-da](https://huggingface.co/Unbabel) has 0 downloads count which is very unlikely. 

### System info

```shell
(hub version is not relevant)
```

**Comment by osanseviero** [comment]
Hey there! 

It seems this model is not from an officially integrated library, so it's not possible for the Hub to know which files count for a download without double counting and inflating downloads. By default, we use `config.json` to determine downloads. For [officially integrated libraries](https://huggingface.co/docs/hub/models-adding-libraries), we're actually able to specify the file, although using `config.json` is the recommendation.

**Comment by ricardorei** [comment]
Thanks for the explanation! Ill study those docs a bit more and see if it makes sense to integrate the library directly.
