### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by greydoubt** [huggingface/hub-docs#786]
add dark mode
use this: #22212C,#454158,#9580FF,#22212C,#454158,#FFFFFF,#8AFF80,#FF5555

**Comment by julien-c** [comment]
?

**Comment by greydoubt** [comment]
The web assets for HF are all white background black text; it is bad for the environment and the eyes for many people. I suggest using the above colour scheme (Dracula) to implement night-mode

**Comment by julien-c** [comment]
we do have a dark mode, have you tried it? (you might need to create an account to toggle it)

<img width="459" alt="image" src="https://github.com/huggingface/hub-docs/assets/326577/4d2dc282-52ec-4bf9-8d7b-2d65b291c613">

**Comment by julien-c** [comment]
if by default it honours your system setting (when logged out), would that fit your use case?

**Comment by greydoubt** [comment]
That would be awesome!

**Comment by krampstudio** [comment]
Dark and system themes are now available everywhere. Enjoy
