### ISSUE TITLE
Completion of existing tasks  🪢❤️  

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/hub-docs#792]
This issue is to complete or improve existing task pages: [hf.co/tasks](https://huggingface.co/tasks/). These pages are wikipedia of machine learning, and are crowdsourced. For each page, you could add an example Space or a more cutting edge model too. You can also add anything you think is useful information about the task to the use cases, task variants and so on. 

On how to start contributing, you can refer to #369 (it has all the information you need to start contributing!) 😊 

Depth Estimation
- [x] Example dataset
- [ ] Metrics and explanation

Image to Image
- [ ] Example dataset
- [ ] Useful resources

Object detection
- [ ] Example datasets

Video classification
- [ ] Example dataset

Zero-shot Image Classification
- [ ] Example dataset

Table Question Answering
- [ ] Task Variants
- [ ] Useful resources

Audio-to-Audio
- [x] Example dataset

Text-to-image
- [ ] Metrics
- [ ] Inference snippet
- [ ] Task variants

Unconditional Image Generation
- [ ] Inference snippet 

Zero-shot Classification
- [ ] Use Cases
- [ ] Metrics
- [x] Most used datasets
- [ ] Example Spaces
- [ ] Subtasks

Reinforcement Learning
- [x] Task Variants
- [ ] Model for the widget
- [x] Small snippet for the task

Feature extraction
- [ ] Metrics
- [ ] Use cases (needs improvement)
- [ ] Example Space

**Comment by kishore-s-15** [comment]
@merveenoyan I would love to contribute to Zero-shot Image Classification and Table Question Answering. Could you kindly assign me for those tasks.

**Comment by balugans** [comment]
@merveenoyan I would love to handle depth estimation.

**Comment by jayant-yadav** [comment]
@merveenoyan I would like to contribute for Text-to-Image. Please assign me that task :)

**Comment by samedovzaur** [comment]
would love to contribute @merveenoyan  :)

**Comment by snehilsanyal** [comment]
Hey @merveenoyan I would like to contribute to Object Detection Task and Image-to-Image task.
For Object Detection I am planning to include a newer model Yolo-NAS as an sample example, will also search for newer datasets. 
For Image-to-Image task I would search for datasets and resources and try to include them. 
Please assign me these tasks. 
PS: First timer in contributing to hub-docs :D

**Comment by younver** [comment]
Hey @merveenoyan, I'd like to contribute. Seems like audio-to-audio task left so I can try my best for that.

**Comment by PalashSharma15** [comment]
HF is a significant part of my learning and work. If there is still room for something, I would love to contribute.

**Comment by merveenoyan** [comment]
@kishore-s-15 @younver @snehilsanyal @samedovzaur @balugans @jayant-yadav sure it works! 

@PalashSharma15 you can still contribute to content side if you think existing task pages are lacking context. 😊

**Comment by Suraj520** [comment]
@merveenoyan  : I guess I'm a bit late to respond as the pending tasks seem to be assigned. Is there something for me, too ?

**Comment by PalashSharma15** [comment]
> @kishore-s-15 @younver @snehilsanyal @samedovzaur @balugans @jayant-yadav sure it works!
> 
> @PalashSharma15 you can still contribute to content side if you think existing task pages are lacking context. 😊

Thanks 🙂. I'll explore and try to add something useful if required.

**Comment by cdreetz** [comment]
Whats not assigned? Or is it necessary to be assigned to contribute?

**Comment by merveenoyan** [comment]
@Suraj520 @cdreetz I think you can simply start contributing as there's plenty of subtasks in the issue

**Comment by Suraj520** [comment]
> @Suraj520 @cdreetz I think you can simply start contributing as there's plenty of subtasks in the issue

Sure @merveenoyan !

**Comment by jayant-yadav** [comment]
@merveenoyan are there any more open tasks available?

**Comment by merveenoyan** [comment]
Hello all 👋  We are closing this issue to move the tasks project to [huggingface.js](https://github.com/huggingface/huggingface.js) github repository. If you want to contribute more tasks, feel free to open a PR there. 
@jayant-yadav sorry for late response. We are adding new tasks these days (`zero-shot-object-detection` and `mask-generation` so you can add them if you feel like it, to huggingface.js repository.
