### ISSUE TITLE
Invalid hyperlink error 404 in Transformer Doc for RayTune

### ISSUE THREAD

**Issue by Joshsamuel101** [huggingface/hub-docs#830]
Greetings,

Small issue here: following the HuggingFace Transformer Docs on Hyperparameter Search using Trainer API, for raytune the hyperlink for 'object_parameter' is now invalid and should be updated. 

The other backends (sigopt, optuna, wandb) have correctly working hyperlinks for the 'object_parameter'. 

Link to doc page:
https://huggingface.co/docs/transformers/hpo_train

Link to specific section:
https://huggingface.co/docs/transformers/hpo_train#how-to-enable-hyperparameter-search-in-example

**Comment by julien-c** [comment]
hi,

would you be able to open a PR to fix this in the transformers repo? in this file: https://github.com/huggingface/transformers/blob/main/docs/source/en/hpo_train.mdx

**Comment by Joshsamuel101** [comment]
Done thanks!

**Comment by julien-c** [comment]
thanks a ton, linking the issue: https://github.com/huggingface/transformers/issues/24135
