### ISSUE TITLE
SEO for docs is rerouting me to old doc website

### ISSUE THREAD

**Issue by davidberenstein1957** [huggingface/hub-docs#867]
**Is your feature request related to a problem? Please describe.**
Googling something like "Hugging Face datasets docs" results in me finding old doc versions and not the new and shiny docs. I know the new docs exist but maybe some other users might have difficulties with the differences.
https://huggingface.co/docs/datasets/v1.11.0/index.html

**Describe the solution you'd like**
Perhaps a warning or a redirect?

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by mishig25** [comment]
When you go to "old" docs, now there is a banner

example page: https://huggingface.co/docs/datasets/v1.18.3/index.html

@davidberenstein1957 thanks a lot for notifying the issue !

<img width="902" alt="image" src="https://github.com/huggingface/hub-docs/assets/11827707/b2e3223c-bcda-4069-ace1-90cc0ade0504">
