### ISSUE TITLE
Schedule Space restart

### ISSUE THREAD

**Issue by Muennighoff** [huggingface/hub-docs#899]
How can one schedule a space restart, e.g. have a space restart every Saturday 1PM? Maybe via git actions?

For context https://huggingface.co/spaces/mteb/leaderboard fetches new data at every restart, so to keep it up-to-date would be great to have an automatic restart e.g. 1x/week.

**Comment by osanseviero** [comment]
You can use https://www.gradio.app/guides/running-background-tasks and run the task with the scheduler once a week

**Comment by julien-c** [comment]
note that we also have a plan to build an easy way to define cronjobs from the Space metadata (a little bit like in GitHub Actions)

from the internal roadmap:

<img width="876" alt="image" src="https://github.com/huggingface/hub-docs/assets/326577/97bb7894-636e-4200-a27b-461a706fa9bf">

cc @christophe-rannou @SBrandeis
