### ISSUE TITLE
Email verification doesn't send. I can't login or change my password. Please help me

### ISSUE THREAD

**Issue by dmitrymailk** [huggingface/hub-docs#908]
my email: dimweb.tech@mail.ru

![image](https://github.com/huggingface/hub-docs/assets/39678439/ef8556fb-86fd-480b-8c49-7e9e687cf4c9)

**Comment by Pierrci** [comment]
hi @dmitrymailk, can you try again? our email provider had blocked your email because it caused a hard bounce in the past (meaning an email couldn't be delivered properly), I manually approved it.

**Comment by dmitrymailk** [comment]
Thank you. It's working. Love you so much ❤️
