### ISSUE TITLE
HuggingFace Space not respecting Streamlit configuration settings

### ISSUE THREAD

**Issue by zachschillaci27** [huggingface/hub-docs#909]
### Describe the bug

My Streamlit HuggingFace Space is not respecting the Streamlit configuration settings I have defined in `.streamlit/config.toml`. Specifically, the app color settings as defined in the `toml` file are not being used in the deployed app. These settings work when running my application locally, so it appears to be a problem with the HF Space deployment.

### System info

```shell
{'huggingface_hub version': '0.14.1',
 'Platform': 'macOS-13.1-arm64-arm-64bit',
 'Python version': '3.10.11',
 'Running in iPython ?': 'Yes',
 'iPython shell': 'ZMQInteractiveShell',
 'Running in notebook ?': 'Yes',
 'Running in Google Colab ?': 'No',
 'Has saved token ?': True,
 'Configured git credential helpers': 'osxkeychain',
 'FastAI': 'N/A',
 'Tensorflow': 'N/A',
 'Torch': '2.0.0',
 'Jinja2': '3.1.2',
 'Graphviz': 'N/A',
 'Pydot': '1.4.2',
 'Pillow': '9.5.0',
 'hf_transfer': 'N/A',
 'gradio': 'N/A',
 'ENDPOINT': 'https://huggingface.co',
 'HF_HUB_OFFLINE': False,
 'HF_HUB_DISABLE_TELEMETRY': False,
 'HF_HUB_DISABLE_PROGRESS_BARS': None,
 'HF_HUB_DISABLE_SYMLINKS_WARNING': False,
 'HF_HUB_DISABLE_EXPERIMENTAL_WARNING': False,
 'HF_HUB_DISABLE_IMPLICIT_TOKEN': False,
 'HF_HUB_ENABLE_HF_TRANSFER': False}
```
```

**Comment by whitphx** [comment]
Hi, thank you for the report!

It seems that the color theme of the Streamlit app is selected as "Light" or "Dark", but not "Custom" by default when you have configured the theme setting of the Hugging Face platform as "Light" or "Dark" so these two theme configs are the same.

It's confusing behavior, so we will work on fixing it. Please be patient for it.

At this moment, as a workaround,
* When you set the HF color theme as "System", or you are logged out, the default Streamlit app color theme is not overridden.
* Also, you can select the "Custom Theme" from the settings dialog that you can access from the top-right menu of the Streamlt app as below.
<table>
<tr>
<td>
<img src="https://github.com/huggingface/hub-docs/assets/3135397/4751cd82-7492-4fd4-8ea4-b195fea045f8" height="400px" >
</td>
<td>
<img src="https://github.com/huggingface/hub-docs/assets/3135397/3c809b3a-360e-4271-9b21-e6802ed83aa0" height="400px">
</td>
</tr>
</table>

**Comment by zachschillaci27** [comment]
> Hi, thank you for the report!
> 
> It seems that the color theme of the Streamlit app is selected as "Light" or "Dark", but not "Custom" by default when you have configured the theme setting of the Hugging Face platform as "Light" or "Dark" so these two theme configs are the same.
> 
> It's confusing behavior, so we will work on fixing it. Please be patient for it.
> 
> At this moment, as a workaround,
> 
> * When you set the HF color theme as "System", or you are logged out, the default Streamlit app color theme is not overridden.
> * Also, you can select the "Custom Theme" from the settings dialog that you can access from the top-right menu of the Streamlt app as below.
> 
> <img alt="" height="400px" src="https://user-images.githubusercontent.com/3135397/258107709-4751cd82-7492-4fd4-8ea4-b195fea045f8.png">	<img alt="" height="400px" src="https://user-images.githubusercontent.com/3135397/258107804-3c809b3a-360e-4271-9b21-e6802ed83aa0.png">

Got it, thanks for the explanation. The workaround is fine for now!

**Comment by whitphx** [comment]
Update: The Hugging Face platform has been updated so that the theme is not overridden when `.streamlit/config.toml` exists.

However, if the user has already visited the page even once, the theme setting has been persisted on their browser's storage and this problem looks still being theme.
It is tracked on Streamlit's side with [this issue](https://github.com/streamlit/streamlit/issues/7118) now and should be fixed in a future release:
