### ISSUE TITLE
Adding missing tasks to `Accelerated Inference` 

### ISSUE THREAD

**Issue by Narsil** [huggingface/hub-docs#91]
**Is your feature request related to a problem? Please describe.**

https://huggingface.co/nielsr/segformer-test-sidewalk-v2

Models like this ARE enabled in the API, yet the button is not displayed, we should add the missing tasks.

**Describe the solution you'd like**

I can open PRs here (documentation needs to be added too in the API).

**Describe alternatives you've considered**

Since the number of tasks is ever increasing and there are many places where we need to sync, maybe we should reconsider the stance on standardized I/O (with a format that both here, the API docs can infer from).
I think here it's not necessarily important to do now since it's a bigger change, but it would help with forward maintenance.

**Additional context**
@mishig25 maybe ?

**Comment by osanseviero** [comment]
I think this might be a duplicate of https://github.com/huggingface/hub-docs/issues/50. This will require a couple of changes since all the code assumes the API structure for NLP tasks. cc @beurkinger as well.

**Comment by mishig25** [comment]
I'll work on it today 👍

**Comment by Narsil** [comment]
Closing this one as it's indeed a duplicate of #50 , Sorry didn't see it.
