### ISSUE TITLE
This link is not rendered correctly

### ISSUE THREAD

**Issue by hysts** [huggingface/hub-docs#914]
https://github.com/huggingface/hub-docs/blob/868966acb479de588d972de29dbb53485e16d45d/docs/hub/spaces-sdks-docker.md?plain=1#L26
![](https://github.com/huggingface/hub-docs/assets/25161192/4a20755c-355d-4e2f-bfeb-c6f509f9199e)
https://huggingface.co/docs/hub/spaces-sdks-docker#secrets-and-variables-management

Not 100% sure, but it might be fixed by removing `.md` in the link, as the following link seems to be rendered correctly.
https://github.com/huggingface/hub-docs/blob/868966acb479de588d972de29dbb53485e16d45d/docs/hub/spaces-sdks-docker.md?plain=1#L53
![](https://github.com/huggingface/hub-docs/assets/25161192/68f23293-9824-4fb8-9323-3008f5becca9)

**Comment by osanseviero** [comment]
cc @mishig25
