### ISSUE TITLE
[hacktoberfest] Model `license:other` challenge

### ISSUE THREAD

**Issue by Wauplin** [huggingface/hub-docs#985]
Issue to keep track of the "Model `license:other` challenge" for the Hacktoberfest 2023.

## Context

The Hugging Face Hub hosts hundreds of thousands of public models and datasets. Public doesn't necessarily mean open-source without any limitations. Authors can define which license applies to the work they share (e.g. [MIT](https://opensource.org/license/mit/), [Apache2.0](https://www.apache.org/licenses/LICENSE-2.0), [OpenRAIL](https://huggingface.co/blog/open_rail), etc.). All users must be able to quickly know which license applies to which model and even to list models with a specific license (e.g. [Apache2.0](https://huggingface.co/models?license=license:apache-2.0&sort=trending)). The Hub relies on the [Model Card](https://huggingface.co/docs/hub/model-cards) to do so. A Model Card is a file attached to a model providing handy information. They are essential for discoverability, reproducibility and sharing. In our case, we will focus on the [metadata](https://huggingface.co/docs/hub/model-cards#model-card-metadata) section of the Model Card. This metadata contains valuable information, including a `license` tag.

In this challenge, we will focus on models that has the license `"other"`. This means that the model has a custom license defined by the author. For example, models from Coqui have their own [coqui-public-model-license](https://coqui.ai/cpml). Historically, this information was not available in the model card metadata. This is now possible by adding the license name and a URL to it:

```yaml
# Example from https://huggingface.co/coqui/XTTS-v1
---
license: other
license_name: coqui-public-model-license
license_link: https://coqui.ai/cpml
---
```

## Instructions

[Check out the instructions details here.](https://github.com/huggingface/hub-docs/blob/main/hacktoberfest_challenges/model_license_other.md)

Feel free to ping @davanstrien or @Wauplin for any question or review.

**Comment by ayan-joshi** [comment]
@Wauplin can you assign me this issue with hacktoberfest label

**Comment by thanktua-spp** [comment]
Hi @Wauplin, I completed a task to update a model license but am unable to update the License [List](https://github.com/huggingface/hub-docs/blob/main/hacktoberfest_challenges/model_license_other.md#model-list). Can you please help? Many thanks

**Comment by Wauplin** [comment]
> @Wauplin can you assign me this issue with hacktoberfest label

> @Wauplin could you please label this issue also with a hacktoberfest label 🤗

Yes! Sorry for the confusion. We just tagged to whole repo as "hacktoberfest" so participation to any PR/issue should not be counted correctly  (might need a few hours delay to appear on https://hacktoberfest.com/).

**Comment by Wauplin** [comment]
> I completed a task to update a model license but am unable to update the License [List](https://github.com/huggingface/hub-docs/blob/main/hacktoberfest_challenges/model_license_other.md#model-list). Can you please help? Many thanks

@thanktua-spp Thank you! You should be able to open a PR on the License list by going to and clicking on the little pen in the top right corner. It will let you contribute and open a PR on this repo (you must be logged in with Github). In the PR you should update the line that you've done with `status` and `pr_url`:
Example: `| Merged | [here](link to your PR) (by @ayan-joshi) | ...`

![image](https://github.com/huggingface/hub-docs/assets/11801849/230a8f8c-919a-489e-b696-7c14fcee1dd3)

**Comment by thanktua-spp** [comment]
thankyou! this worked.

**Comment by pksX01** [comment]
@Wauplin Could you please review this PR #1001 .

**Comment by Wauplin** [comment]
> @Wauplin Could you please review this PR #1001 .

Yes for sure! Thanks for your contribution :hugs:

**Comment by Shreyash-0699** [comment]
@Wauplin could you please review this PR #1009

**Comment by Wauplin** [comment]
> @Wauplin could you please review this PR #1009

Sure, of course! PR approved and merged :tada: Thank you for opening it :hugs:

**Comment by Ashish-Soni08** [comment]
Hey @Wauplin, Hope you are doing great! Could you please review this PR #1054

**Comment by Wauplin** [comment]
> Hey @Wauplin, Hope you are doing great! Could you please review this PR https://github.com/huggingface/hub-docs/pull/1054

Yes of course! Thanks for opening the PR :pray: 
I just merged it so congratulation for this first contribution on HF :hugs:

**Comment by Wauplin** [comment]
Wow, you were on fire @Ashish-Soni08! :fire: :fire: :fire: I merged 4 of them and commented on 3 others. Thanks a lot!!

**Comment by Ashish-Soni08** [comment]
Thank you @Wauplin. I made the required/suggested changes to 2 and closed 1, in the ones that are left.

**Comment by Wauplin** [comment]
Perfect! 6 merged, 1 closed then. Thanks again! :)
